namespace Takatora.Core

open System.IO

/// Generates and writes the starter `.ci/` tree (project.toml + flows.toml)
/// for a new project. Shared by the CLI `init` command and the GUI Add-
/// Project wizard so both emit identical, immediately-runnable scaffolding.
[<RequireQualifiedAccess>]
module Scaffold =

    let private engineToken (engine: EngineKind) : string =
        match engine with
        | EngineKind.Unreal -> "unreal"
        | EngineKind.Unity  -> "unity"
        | EngineKind.Godot  -> "godot"

    /// Minimal valid project.toml — just the keys `TomlConfig.parseProject`
    /// requires (project.name / working_dir + engine.type) plus a history
    /// default. Engine paths are left for autodetection.
    let projectToml (name: string) (engine: EngineKind) : string =
        let esc (s: string) = s.Replace("\\", "\\\\").Replace("\"", "\\\"")
        String.concat "\n" [
            "# Generated by Takatora."
            "# Edit to point at your engine install / project file as needed."
            ""
            "[project]"
            sprintf "name = \"%s\"" (esc name)
            "working_dir = \".\""
            ""
            "[engine]"
            sprintf "type = \"%s\"" (engineToken engine)
            ""
            "[history]"
            "keep_last_n_runs = 50"
            ""
        ]

    /// Starter flows.toml with one immediately-runnable flow (`notify.console`
    /// — the only engine-agnostic builtin), so a fresh project isn't stuck at
    /// "no flows.toml" regardless of the chosen engine.
    let flowsToml () : string =
        String.concat "\n" [
            "# Generated by Takatora."
            "# A starter flow you can run right away; replace with your real"
            "# build/cook/export steps as you wire up the engine."
            ""
            "[[flow]]"
            "id = \"smoke\""
            "name = \"Smoke test (notify only)\""
            ""
            "[flow.vars]"
            "message = { type = \"string\", default = \"hello from takatora\" }"
            ""
            "[[flow.steps]]"
            "type = \"notify.console\""
            ""
        ]

    /// What `writeCi` did. A file flagged `false` already existed and was
    /// left untouched (never clobbered).
    type Outcome = {
        CiDir: string
        ProjectTomlCreated: bool
        FlowsTomlCreated: bool
    }

    /// Create `<dir>/.ci/` and write project.toml + flows.toml when absent.
    /// Existing files are never overwritten. Returns which were created.
    let writeCi (dir: string) (name: string) (engine: EngineKind) : Outcome =
        let ciDir = Path.Combine(dir, ".ci")
        Directory.CreateDirectory ciDir |> ignore
        let projectPath = Path.Combine(ciDir, "project.toml")
        let flowsPath   = Path.Combine(ciDir, "flows.toml")
        let pCreated =
            if File.Exists projectPath then false
            else File.WriteAllText(projectPath, projectToml name engine); true
        let fCreated =
            if File.Exists flowsPath then false
            else File.WriteAllText(flowsPath, flowsToml ()); true
        { CiDir = ciDir; ProjectTomlCreated = pCreated; FlowsTomlCreated = fCreated }
