namespace Takatora.Core

open System.IO

/// Generates and writes the starter `.takatora/` tree (project.toml + flows.toml)
/// for a new project. Shared by the CLI `init` command and the GUI Add-
/// Project wizard so both emit identical, immediately-runnable scaffolding.
[<RequireQualifiedAccess>]
module Scaffold =

    let private engineToken (engine: EngineKind) : string =
        match engine with
        | EngineKind.Unreal -> "unreal"
        | EngineKind.Unity  -> "unity"
        | EngineKind.Godot  -> "godot"

    /// Minimal valid project.toml — just the keys `TomlConfig.parseProject`
    /// requires (project.name / working_dir + engine.type) plus a history
    /// default. Engine paths are left for autodetection.
    let projectToml (name: string) (engine: EngineKind) : string =
        let esc (s: string) = s.Replace("\\", "\\\\").Replace("\"", "\\\"")
        String.concat "\n" [
            "# Generated by Takatora."
            "# Edit to point at your engine install / project file as needed."
            ""
            "[project]"
            sprintf "name = \"%s\"" (esc name)
            "working_dir = \".\""
            ""
            "[engine]"
            sprintf "type = \"%s\"" (engineToken engine)
            ""
            "[history]"
            "keep_last_n_runs = 50"
            ""
        ]

    /// Starter flows.toml: an engine-agnostic `smoke` flow that runs with zero
    /// setup, plus engine-specific preset flows (build/package/export + clean)
    /// wired to the matching builtin task family. Presets carry sensible
    /// defaults and `# ←` comments where a project-specific value (UE target,
    /// Unity build method, Godot export preset) must be filled in.
    let flowsToml (name: string) (engine: EngineKind) : string =
        let esc (s: string) = s.Replace("\\", "\\\\").Replace("\"", "\\\"")
        let n = esc name
        let header = [
            "# Generated by Takatora."
            "# `smoke` runs immediately; the engine presets below are starting"
            "# points — adjust paths/targets and the marked (# ←) values."
            ""
        ]
        let smoke = [
            "[[flow]]"
            "id = \"smoke\""
            "name = \"Smoke test (notify only)\""
            ""
            "[flow.vars]"
            "message = { type = \"string\", default = \"hello from takatora\" }"
            ""
            "[[flow.steps]]"
            "type = \"notify.console\""
            ""
        ]
        let unreal = [
            "# Non-unity compile check (drives UBT with -DisableUnity)."
            "[[flow]]"
            "id = \"compile\""
            "name = \"Non-unity compile check\""
            ""
            "[[flow.steps]]"
            "type = \"ue.build_nonunity\""
            ""
            "# Windows package via UAT BuildCookRun (build + cook + stage + pak)."
            "[[flow]]"
            "id = \"package\""
            "name = \"Windows package (BuildCookRun)\""
            ""
            "[flow.vars]"
            "configuration = { type = \"enum\", values = [\"Development\", \"DebugGame\", \"Shipping\", \"Test\"], default = \"Development\", description = \"Build configuration — Shipping for release builds.\" }"
            ""
            "[[flow.steps]]"
            "type = \"ue.build_cook_run\""
            "configuration = \"${vars.configuration}\""
            "platform = \"Win64\""
            sprintf "target = \"%s\"  # ← your game target (often the project name)" n
            "archive_dir = \"Package/Windows\""
            "extra_uat_args = [\"-noP4\", \"-pak\", \"-prereqs\", \"-allmaps\", \"-targetplatform=Win64\"]"
            ""
            "# Clean Intermediate + Binaries."
            "[[flow]]"
            "id = \"clean\""
            "name = \"Clean (intermediate + binaries)\""
            ""
            "[[flow.steps]]"
            "type = \"ue.clean\""
            "preset = \"safe\""
            ""
        ]
        let unity = [
            "# Batch build. Your editor script does the real work — point"
            "# build_method at a public static C# method that builds the player."
            "[[flow]]"
            "id = \"build\""
            "name = \"Build (StandaloneWindows64)\""
            ""
            "[flow.vars]"
            "build_target = { type = \"string\", default = \"StandaloneWindows64\" }"
            ""
            "[[flow.steps]]"
            "type = \"unity.build\""
            "build_target = \"${vars.build_target}\""
            "build_method = \"BuildScripts.BuildAll\"  # ← your editor build method"
            sprintf "output = \"Build/Windows/%s.exe\"" n
            ""
            "# Clean Temp + obj (safe preset)."
            "[[flow]]"
            "id = \"clean\""
            "name = \"Clean (Temp + obj)\""
            ""
            "[[flow.steps]]"
            "type = \"unity.clean\""
            "preset = \"safe\""
            ""
        ]
        let godot = [
            "# Headless export. `preset` must match a preset name in your"
            "# export_presets.cfg."
            "[[flow]]"
            "id = \"export\""
            "name = \"Export (Windows Desktop)\""
            ""
            "[[flow.steps]]"
            "type = \"godot.export\""
            "preset = \"Windows Desktop\"  # ← match export_presets.cfg"
            sprintf "output = \"Build/Windows/%s.exe\"" n
            ""
            "# Clean cache (.godot/.import) + build output."
            "[[flow]]"
            "id = \"clean\""
            "name = \"Clean (cache + build)\""
            ""
            "[[flow.steps]]"
            "type = \"godot.clean\""
            "preset = \"pre_release\""
            ""
        ]
        let enginePresets =
            match engine with
            | EngineKind.Unreal -> unreal
            | EngineKind.Unity  -> unity
            | EngineKind.Godot  -> godot
        String.concat "\n" (header @ smoke @ enginePresets)

    /// What `writeCi` did. A file flagged `false` already existed and was
    /// left untouched (never clobbered).
    type Outcome = {
        CiDir: string
        ProjectTomlCreated: bool
        FlowsTomlCreated: bool
    }

    /// Create `<dir>/.takatora/` and write project.toml + flows.toml when absent.
    /// Existing files are never overwritten. Returns which were created.
    let writeCi (dir: string) (name: string) (engine: EngineKind) : Outcome =
        let ciDir = Path.Combine(dir, ".takatora")
        Directory.CreateDirectory ciDir |> ignore
        let projectPath = Path.Combine(ciDir, "project.toml")
        let flowsPath   = Path.Combine(ciDir, "flows.toml")
        let pCreated =
            if File.Exists projectPath then false
            else File.WriteAllText(projectPath, projectToml name engine); true
        let fCreated =
            if File.Exists flowsPath then false
            else File.WriteAllText(flowsPath, flowsToml name engine); true
        { CiDir = ciDir; ProjectTomlCreated = pCreated; FlowsTomlCreated = fCreated }
