module Takatora.Gui.State

open System
open System.IO
open Elmish
open Avalonia.Threading
open Takatora.Core

/// Project lookup key inside the GUI. The registry uses `Name` as the
/// stable identifier (per ProjectRegistry.find docs), so we mirror that
/// rather than introducing a separate id type.
type ProjectId = string

/// Run id (mirrors RunHistoryEntry.RunId). Carried alongside ProjectId
/// in RunDetail tabs because RunHistory.findRun needs the project's
/// working dir to locate the run.
type RunId = string

/// Client-side identifier for an in-flight LiveRun. Generated by the
/// GUI at RunFlow time and used as the LiveRun tab's key, because the
/// runner's RunId isn't known until Run.execute returns.
type LiveRunKey = Guid

/// State of one LiveRun tab. Captures enough to render before, during,
/// and after the run completes, without inventing a third "Cancelled
/// by tab close" state — closing the tab doesn't cancel the run, just
/// stops the GUI from observing it.
type LiveRunPhase =
    | LivePending
    | LiveCompleted of Result<RunOutcome, RunFailure>

type LiveRunState = {
    ProjectId: ProjectId
    FlowId: string
    StartedAt: DateTimeOffset
    Phase: LiveRunPhase
}

/// Root tab variants. Home + Project + RunDetail + LiveRun are wired;
/// Settings (the app-wide one from gui.md) will land later.
type RootTab =
    | Home
    | Project of ProjectId
    | RunDetail of ProjectId * RunId
    | LiveRun of LiveRunKey

/// Sub-tabs inside a Project tab. Per gui.md these are plain TabControl
/// territory (only the root strip is custom), but we keep the active
/// sub-tab in the model so re-focusing a Project tab restores its
/// position rather than resetting to Flows.
type ProjectSubTab =
    | ProjectFlows
    | ProjectHistory
    | ProjectSettings

/// Result of trying to read a project's `.ci/flows.toml`. The three
/// outcomes need distinct UX — missing file is a setup hint, parse
/// failure is a config bug to surface, success is the happy path.
type FlowsLoad =
    | FlowsOk of Flow list
    | FlowsMissing
    | FlowsError of string

/// Same shape as FlowsLoad but for `.ci/project.toml`. Project info
/// is technically validated at `project add` time, but the file may
/// have been edited or deleted between registration and now.
type ProjectInfoLoad =
    | ProjectInfoOk of Project
    | ProjectInfoMissing
    | ProjectInfoError of string

type Model = {
    OpenTabs: RootTab list
    ActiveTab: RootTab
    Projects: ProjectRegistration list
    /// Per-Project-tab active sub-tab. Missing key means "default" (Flows).
    ProjectSubTabs: Map<ProjectId, ProjectSubTab>
    /// Cached `RunHistory.load` results, keyed by project id. Loaded
    /// lazily on OpenProject so initial app startup doesn't pay for
    /// every project's runs dir.
    ProjectHistory: Map<ProjectId, RunHistoryEntry list>
    /// Cached `TomlConfig.loadFlows` results, keyed by project id.
    /// Loaded on OpenProject alongside history.
    ProjectFlows: Map<ProjectId, FlowsLoad>
    /// Cached `TomlConfig.loadProject` results, keyed by project id.
    /// Loaded on OpenProject alongside flows.
    ProjectInfo: Map<ProjectId, ProjectInfoLoad>
    /// Cached `RunHistory.findRun` results for open RunDetail tabs,
    /// keyed by (project, run id). Loaded on OpenRunDetail, dropped
    /// when the corresponding tab closes.
    RunDetails: Map<ProjectId * RunId, RunHistoryEntry * StepSummary list>
    /// Live state of every LiveRun tab the user has kicked off. Entries
    /// are added by RunFlow and removed by LiveRunCompleted (which also
    /// drops the entry if its tab has been closed).
    LiveRuns: Map<LiveRunKey, LiveRunState>
}

type Msg =
    | RefreshProjects
    | OpenProject of ProjectId
    | ActivateTab of RootTab
    | CloseTab of RootTab
    | ActivateSubTab of ProjectId * ProjectSubTab
    | RefreshHistory of ProjectId
    | RefreshFlows of ProjectId
    | RefreshProjectInfo of ProjectId
    | OpenRunDetail of ProjectId * RunId
    | RunFlow of ProjectId * flowId:string
    | LiveRunCompleted of LiveRunKey * Result<RunOutcome, RunFailure>
    | LiveRunFailed    of LiveRunKey * exn

let init () : Model * Cmd<Msg> =
    { OpenTabs       = [ Home ]
      ActiveTab      = Home
      Projects       = ProjectRegistry.load ()
      ProjectSubTabs = Map.empty
      ProjectHistory = Map.empty
      ProjectFlows   = Map.empty
      ProjectInfo    = Map.empty
      RunDetails     = Map.empty
      LiveRuns       = Map.empty },
    Cmd.none

let private moveOrAppend (tab: RootTab) (tabs: RootTab list) : RootTab list =
    if List.contains tab tabs then tabs else tabs @ [ tab ]

/// Compute the post-close tab list plus the next active tab. When the
/// closed tab was the active one, prefer the tab that was to its right
/// (browser convention); fall back to the previous tab, finally Home.
let private closeAndPickActive
        (target: RootTab) (active: RootTab) (tabs: RootTab list)
        : RootTab list * RootTab =
    if target = Home then tabs, active
    else
        match List.tryFindIndex ((=) target) tabs with
        | None -> tabs, active
        | Some idx ->
            let newTabs = List.filter ((<>) target) tabs
            let newActive =
                if active <> target then active
                elif idx < List.length newTabs then newTabs.[idx]
                else
                    match newTabs with
                    | [] -> Home
                    | _  -> List.last newTabs
            newTabs, newActive

/// Look up the active sub-tab for a project, defaulting to Flows. Used
/// by views; not used by `update` (which writes the map directly).
let projectSubTab (pid: ProjectId) (model: Model) : ProjectSubTab =
    Map.tryFind pid model.ProjectSubTabs
    |> Option.defaultValue ProjectFlows

let private projectRoot
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : string option =
    projects
    |> List.tryFind (fun (p: ProjectRegistration) -> p.Name = pid)
    |> Option.map (fun p -> p.Path)

let private loadHistoryFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : RunHistoryEntry list =
    match projectRoot pid projects with
    | Some root -> RunHistory.load root
    | None      -> []

/// Read and classify `.ci/flows.toml` for the given project. We keep
/// the three outcomes distinct because each maps to a different UX:
/// missing → "no flows yet, here's how to add one"; error → "your
/// flows.toml has a bug, here's the message"; ok → render the list.
let private loadFlowsFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : FlowsLoad =
    match projectRoot pid projects with
    | None -> FlowsError (sprintf "Project '%s' not in registry" pid)
    | Some root ->
        let path = Path.Combine(root, ".ci", "flows.toml")
        if not (File.Exists path) then FlowsMissing
        else
            try FlowsOk (TomlConfig.loadFlows path)
            with ex -> FlowsError ex.Message

/// Resolve the Tasks SDK assembly + builtin tasks dir from the host
/// process layout. Same defaults the CLI uses; works here because the
/// GUI project-references Takatora.Tasks + Takatora.Tasks.Builtin, so
/// Tasks.dll + builtin-tasks/ get copied next to the GUI executable.
let private sdkAssemblyPath () =
    Path.Combine(AppContext.BaseDirectory, "Takatora.Tasks.dll")

let private builtinTasksDir () =
    Path.Combine(AppContext.BaseDirectory, "builtin-tasks")

/// Same shape as `loadFlowsFor` but for `.ci/project.toml`.
let private loadProjectInfoFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : ProjectInfoLoad =
    match projectRoot pid projects with
    | None -> ProjectInfoError (sprintf "Project '%s' not in registry" pid)
    | Some root ->
        let path = Path.Combine(root, ".ci", "project.toml")
        if not (File.Exists path) then ProjectInfoMissing
        else
            try ProjectInfoOk (TomlConfig.loadProject path)
            with ex -> ProjectInfoError ex.Message

let update (msg: Msg) (model: Model) : Model * Cmd<Msg> =
    match msg with
    | RefreshProjects ->
        { model with Projects = ProjectRegistry.load () }, Cmd.none
    | OpenProject pid ->
        let tab = Project pid
        let history =
            if Map.containsKey pid model.ProjectHistory then model.ProjectHistory
            else Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory
        let flows =
            if Map.containsKey pid model.ProjectFlows then model.ProjectFlows
            else Map.add pid (loadFlowsFor pid model.Projects) model.ProjectFlows
        let info =
            if Map.containsKey pid model.ProjectInfo then model.ProjectInfo
            else Map.add pid (loadProjectInfoFor pid model.Projects) model.ProjectInfo
        { model with
            OpenTabs       = moveOrAppend tab model.OpenTabs
            ActiveTab      = tab
            ProjectHistory = history
            ProjectFlows   = flows
            ProjectInfo    = info },
        Cmd.none
    | ActivateTab tab ->
        if List.contains tab model.OpenTabs then
            { model with ActiveTab = tab }, Cmd.none
        else model, Cmd.none
    | CloseTab tab ->
        let newTabs, newActive = closeAndPickActive tab model.ActiveTab model.OpenTabs
        // Drop per-tab caches when the corresponding tab closes; reopen
        // reloads from disk anyway, and keeping stale entries would let
        // the cache grow without bound across a long session.
        //
        // LiveRuns entries are intentionally NOT dropped here for tabs
        // closed while still Pending — LiveRunCompleted needs the entry
        // to find the project id for the post-run history refresh. It
        // drops the entry itself when it sees the tab is no longer in
        // OpenTabs.
        let subTabs, history, flows, info, details =
            match tab with
            | Project pid ->
                Map.remove pid model.ProjectSubTabs,
                Map.remove pid model.ProjectHistory,
                Map.remove pid model.ProjectFlows,
                Map.remove pid model.ProjectInfo,
                model.RunDetails
            | RunDetail (pid, runId) ->
                model.ProjectSubTabs,
                model.ProjectHistory,
                model.ProjectFlows,
                model.ProjectInfo,
                Map.remove (pid, runId) model.RunDetails
            | LiveRun _ | Home ->
                model.ProjectSubTabs,
                model.ProjectHistory,
                model.ProjectFlows,
                model.ProjectInfo,
                model.RunDetails
        { model with
            OpenTabs       = newTabs
            ActiveTab      = newActive
            ProjectSubTabs = subTabs
            ProjectHistory = history
            ProjectFlows   = flows
            ProjectInfo    = info
            RunDetails     = details },
        Cmd.none
    | ActivateSubTab (pid, sub) ->
        { model with ProjectSubTabs = Map.add pid sub model.ProjectSubTabs }, Cmd.none
    | RefreshHistory pid ->
        { model with
            ProjectHistory = Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory },
        Cmd.none
    | RefreshFlows pid ->
        { model with
            ProjectFlows = Map.add pid (loadFlowsFor pid model.Projects) model.ProjectFlows },
        Cmd.none
    | RefreshProjectInfo pid ->
        { model with
            ProjectInfo = Map.add pid (loadProjectInfoFor pid model.Projects) model.ProjectInfo },
        Cmd.none
    | OpenRunDetail (pid, runId) ->
        let tab = RunDetail (pid, runId)
        let key = pid, runId
        let details =
            if Map.containsKey key model.RunDetails then model.RunDetails
            else
                match projectRoot pid model.Projects with
                | None -> model.RunDetails
                | Some root ->
                    match RunHistory.findRun root runId with
                    | Some data -> Map.add key data model.RunDetails
                    | None      -> model.RunDetails
        { model with
            OpenTabs   = moveOrAppend tab model.OpenTabs
            ActiveTab  = tab
            RunDetails = details },
        Cmd.none
    | RunFlow (pid, flowId) ->
        // Async in-process run: spin up a LiveRun tab immediately so
        // the user sees the dispatch land, then schedule Run.execute on
        // the thread pool. LiveRunCompleted (or LiveRunFailed on an
        // unexpected exn) closes the loop by updating the tab's phase
        // and reloading history.
        match projectRoot pid model.Projects with
        | None -> model, Cmd.none
        | Some root ->
            let key = Guid.NewGuid()
            let tab = LiveRun key
            let liveState = {
                ProjectId = pid
                FlowId    = flowId
                StartedAt = DateTimeOffset.UtcNow
                Phase     = LivePending
            }
            let opts : Run.Options = {
                WorkingDir       = root
                FlowId           = flowId
                VarOverrides     = Map.empty
                SdkAssemblyPath  = sdkAssemblyPath ()
                BuiltinTasksDir  = builtinTasksDir ()
                UserTasksDir     = None
            }
            // Run on the thread pool, then marshal the result message
            // back onto the Avalonia UI thread before dispatching.
            //
            // We deliberately do NOT use Cmd.OfAsync.either here: in
            // Elmish, the dispatch loop runs `setState` (→ FuncUI's
            // host.Update → Avalonia view rebuild) on whatever thread
            // calls `dispatch`. FuncUI.Elmish 1.5.1's withHost does not
            // marshal, so dispatching from the thread-pool thread would
            // rebuild the view off the UI thread and crash the whole
            // app. Dispatcher.UIThread.Post guarantees the dispatch —
            // and thus the re-render — happens on the UI thread.
            let cmd : Cmd<Msg> =
                [ fun dispatch ->
                    async {
                        do! Async.SwitchToThreadPool ()
                        let msg =
                            try LiveRunCompleted (key, Run.execute opts)
                            with ex -> LiveRunFailed (key, ex)
                        Dispatcher.UIThread.Post(fun () -> dispatch msg)
                    }
                    |> Async.Start ]
            { model with
                OpenTabs  = moveOrAppend tab model.OpenTabs
                ActiveTab = tab
                LiveRuns  = Map.add key liveState model.LiveRuns },
            cmd
    | LiveRunCompleted (key, result) ->
        match Map.tryFind key model.LiveRuns with
        | None -> model, Cmd.none  // should not happen; guard.
        | Some state ->
            let pid = state.ProjectId
            // Always refresh history — even if the LiveRun tab itself
            // was closed before completion, the Project tab may still
            // be open and the user would expect the new run to appear.
            let newHistory =
                Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory
            // Keep the LiveRuns entry around if the tab is still open
            // (so the view can render the Completed phase); otherwise
            // drop it to bound the map.
            let newLiveRuns =
                if List.contains (LiveRun key) model.OpenTabs then
                    Map.add key { state with Phase = LiveCompleted result } model.LiveRuns
                else
                    Map.remove key model.LiveRuns
            { model with
                LiveRuns       = newLiveRuns
                ProjectHistory = newHistory },
            Cmd.none
    | LiveRunFailed (key, ex) ->
        // Unexpected exception from the async machinery itself (not a
        // RunFailure, which is already a Result Error). Synthesize an
        // InternalError so the UI can show something rather than just
        // freezing in Pending.
        match Map.tryFind key model.LiveRuns with
        | None -> model, Cmd.none
        | Some state ->
            let result = Error (RunFailure.InternalError ex.Message)
            let pid = state.ProjectId
            let newHistory =
                Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory
            let newLiveRuns =
                if List.contains (LiveRun key) model.OpenTabs then
                    Map.add key { state with Phase = LiveCompleted result } model.LiveRuns
                else
                    Map.remove key model.LiveRuns
            { model with
                LiveRuns       = newLiveRuns
                ProjectHistory = newHistory },
            Cmd.none
