module Takatora.Gui.State

open System
open System.IO
open System.Text.Json
open Elmish
open Avalonia.Threading
open Takatora.Core

/// Project lookup key inside the GUI. The registry uses `Name` as the
/// stable identifier (per ProjectRegistry.find docs), so we mirror that
/// rather than introducing a separate id type.
type ProjectId = string

/// Run id (mirrors RunHistoryEntry.RunId). Carried alongside ProjectId
/// in RunDetail tabs because RunHistory.findRun needs the project's
/// working dir to locate the run.
type RunId = string

/// Client-side identifier for an in-flight LiveRun. Generated by the
/// GUI at RunFlow time and used as the LiveRun tab's key, because the
/// runner's RunId isn't known until Run.execute returns.
type LiveRunKey = Guid

/// State of one LiveRun tab. Captures enough to render before, during,
/// and after the run completes, without inventing a third "Cancelled
/// by tab close" state — closing the tab doesn't cancel the run, just
/// stops the GUI from observing it.
type LiveRunPhase =
    | LivePending
    | LiveCompleted of Result<RunOutcome, RunFailure>

/// Status of a single step as observed live from events.ndjson. Distinct
/// from Core.StepStatus because mid-run we have a "still running" state
/// the persisted record never has.
type LiveStepStatus =
    | StepRunning
    | StepOk
    | StepFailed
    | StepSkipped
    | StepCancelled

type LiveStep = {
    Id: string
    Type: string
    Status: LiveStepStatus
    DurationSec: float
}

/// A snapshot parsed from a run's events.ndjson + log.txt by the live
/// poller. Replaces the LiveRunState's previous snapshot wholesale on
/// each tick (cheap — these files are tiny).
type LiveProgress = {
    /// Discovered run dir, once the poller has matched it. None until then.
    RunDir: string option
    Steps: LiveStep list
    /// Tail of log.txt (most recent lines, capped).
    LogTail: string list
    /// True once a `run.end` event has been observed.
    Ended: bool
}

module LiveProgress =
    let empty = { RunDir = None; Steps = []; LogTail = []; Ended = false }

type LiveRunState = {
    ProjectId: ProjectId
    FlowId: string
    StartedAt: DateTimeOffset
    Phase: LiveRunPhase
    /// Latest live snapshot from the poller (steps + log tail).
    Progress: LiveProgress
    /// Set once the user clicks Cancel (we've written the CANCEL flag).
    /// Drives the button's "Cancelling…" / disabled state; the run keeps
    /// going until the runner observes the flag and tears down.
    CancelRequested: bool
}

/// A project's active "watch": auto-run FlowId when the git HEAD moves.
/// LastHead is the commit we last acted on (the poll fires when HEAD differs).
type WatchInfo = {
    FlowId: string
    LastHead: string option
}

/// Root tab variants. Home + Project + RunDetail + LiveRun are wired;
/// Settings (the app-wide one from gui.md) will land later.
type RootTab =
    | Home
    | Project of ProjectId
    | RunDetail of ProjectId * RunId
    | LiveRun of LiveRunKey

/// Sub-tabs inside a Project tab. Per gui.md these are plain TabControl
/// territory (only the root strip is custom), but we keep the active
/// sub-tab in the model so re-focusing a Project tab restores its
/// position rather than resetting to Flows.
type ProjectSubTab =
    | ProjectFlows
    | ProjectHistory
    | ProjectSettings

/// Result of trying to read a project's `.ci/flows.toml`. The three
/// outcomes need distinct UX — missing file is a setup hint, parse
/// failure is a config bug to surface, success is the happy path.
type FlowsLoad =
    | FlowsOk of Flow list
    | FlowsMissing
    | FlowsError of string

/// Add-Project wizard form state. Present (Some) when the wizard panel
/// on Home is open; None when collapsed. Kept in the model because
/// Elmish owns all UI state — there's no local widget state to lean on.
type AddProjectForm = {
    Dir: string
    Name: string
    Engine: EngineKind
    /// Last submission error, surfaced inline under the form. Cleared on
    /// the next edit/submit so a fixed mistake doesn't keep nagging.
    Error: string option
}

/// "Run with parameters" dialog state. Present (Some) while the modal
/// overlay is open. `Values` holds the raw editing text per var name
/// (bool as "true"/"false", enum as the selected value); parsing into
/// typed `VarOverrides` happens at confirm so partial numeric input
/// doesn't fight the user mid-keystroke.
type RunDialogState = {
    ProjectId: ProjectId
    FlowId: string
    /// Dialog-renderable vars (see State.isDialogVarKind), declaration order.
    Vars: FlowVar list
    Values: Map<string, string>
    /// Per-list-var item texts (raw, one per array element). Parsed into a
    /// TArray per the list's item kind at confirm.
    Lists: Map<string, string list>
    /// Bool var names referenced by a step's `when` — rendered in a top
    /// "Toggles" section (the rest go under "Parameters").
    Toggles: Set<string>
    /// "Save as new default" — write the changed values back to flows.toml
    /// on Run. Off by default.
    SaveDefaults: bool
    /// Secret var names the user has flagged to persist to the keychain on
    /// Run. Initialised on: already-stored secrets default to remembered.
    Remember: Set<string>
    /// Secret var names that currently have a keychain entry (drives the
    /// "saved ✓" / Forget affordance). Updated when Forget fires.
    Stored: Set<string>
    /// Validation error from the last confirm attempt, cleared on edit.
    Error: string option
}

/// Same shape as FlowsLoad but for `.ci/project.toml`. Project info
/// is technically validated at `project add` time, but the file may
/// have been edited or deleted between registration and now.
type ProjectInfoLoad =
    | ProjectInfoOk of Project
    | ProjectInfoMissing
    | ProjectInfoError of string

type Model = {
    OpenTabs: RootTab list
    ActiveTab: RootTab
    Projects: ProjectRegistration list
    /// Per-Project-tab active sub-tab. Missing key means "default" (Flows).
    ProjectSubTabs: Map<ProjectId, ProjectSubTab>
    /// Cached `RunHistory.load` results, keyed by project id. Loaded
    /// lazily on OpenProject so initial app startup doesn't pay for
    /// every project's runs dir.
    ProjectHistory: Map<ProjectId, RunHistoryEntry list>
    /// Cached `TomlConfig.loadFlows` results, keyed by project id.
    /// Loaded on OpenProject alongside history.
    ProjectFlows: Map<ProjectId, FlowsLoad>
    /// Cached `TomlConfig.loadProject` results, keyed by project id.
    /// Loaded on OpenProject alongside flows.
    ProjectInfo: Map<ProjectId, ProjectInfoLoad>
    /// Engine kind per registered project (from project.toml's [engine].type),
    /// loaded eagerly whenever the project list changes so the Home list can
    /// tint each project name by engine — cheap (a small TOML parse, no runs
    /// scan). Missing/unparseable projects are simply absent (no tint).
    ProjectEngines: Map<ProjectId, EngineKind>
    /// Cached keychain secret var names per project (for the Settings
    /// manager). Refreshed when Settings is opened/refreshed and on
    /// delete, so the list stays a pure function of model state.
    ProjectSecrets: Map<ProjectId, string list>
    /// Cached `RunHistory.findRun` results for open RunDetail tabs,
    /// keyed by (project, run id). Loaded on OpenRunDetail, dropped
    /// when the corresponding tab closes. Tuple: entry, step summaries,
    /// step outputs (step id → name → value), and the run's full log.txt
    /// lines (so a past run is reviewable in RunDetail).
    RunDetails: Map<ProjectId * RunId, RunHistoryEntry * StepSummary list * Map<string, Map<string, string>> * string list>
    /// Per-RunDetail log search query (a find — jumps to matches, does not
    /// filter) and the current match index (the view wraps it mod count).
    RunLogFilter: Map<ProjectId * RunId, string>
    RunLogMatchIdx: Map<ProjectId * RunId, int>
    /// Projects with an "Open in editor" launch in flight. Opening goes
    /// through the OS shell and the target app (UE editor / Rider) can take
    /// tens of seconds to show a window; without feedback the user re-clicks,
    /// queueing several launches that all open at once. While a project is in
    /// this set its button is disabled ("Opening…") and repeat clicks are
    /// ignored; a timed ClearOpeningEditor removes it.
    OpeningEditors: Set<ProjectId>
    /// Same single-flight guard for "Open in IDE" launches.
    OpeningIde: Set<ProjectId>
    /// Machine-local app settings (the "Open in IDE" command template lives
    /// here). Loaded at startup, rewritten by the Settings editor.
    AppSettings: AppSettings
    /// In-progress text of the global IDE-command editor (Settings). Seeded
    /// from AppSettings.IdeCommand; persisted on Save.
    IdeCommandDraft: string
    /// Detected IDE presets (populated on demand by the Settings "Detect"
    /// button) the user can one-click into the command template.
    IdeCandidates: IdeCandidate list
    /// In-progress text of the Godot search-paths editor (one dir per line).
    GodotSearchPathsDraft: string
    /// Detected Godot executables (PATH + configured search paths), for the
    /// user to pick the machine-level Godot from.
    GodotCandidates: DetectedEngine list
    /// The flow step whose describe-schema Inspector is open: (project, flow
    /// id, step index). None = no Inspector.
    SelectedStep: (ProjectId * string * int) option
    /// Describe schema cache, keyed by `stepSchemaKey` (task path + mtime).
    StepSchemas: Map<string, Result<DescribeSchema, string>>
    /// Schema keys with a describe spawn in flight (shows "inspecting…").
    StepSchemasLoading: Set<string>
    /// In-progress "add step" task-type text, keyed by (project, flow id).
    AddStepDraft: Map<ProjectId * string, string>
    /// Flow cards whose step list is expanded (collapsed by default — keeps
    /// the Flows tab low-noise; steps + editing live behind the expander).
    ExpandedFlows: Set<ProjectId * string>
    /// Expanded flows currently in edit mode (step move/delete/add controls).
    EditingFlows: Set<ProjectId * string>
    /// Settings sub-tab search query (filters setting rows/sections by text).
    SettingsFilter: string
    /// Projects being watched (auto-run a flow on new commits), keyed by
    /// project id. One watched flow per project. Runtime-only (not persisted).
    Watches: Map<ProjectId, WatchInfo>
    /// Live state of every LiveRun tab the user has kicked off. Entries
    /// are added by RunFlow and removed by LiveRunCompleted (which also
    /// drops the entry if its tab has been closed).
    LiveRuns: Map<LiveRunKey, LiveRunState>
    /// Add-Project wizard state. None = panel collapsed; Some = open with
    /// in-progress field values. Lives on the Home tab.
    AddProject: AddProjectForm option
    /// The project whose tabs the root strip is currently scoped to.
    /// Sticky: opening/activating a project's tab sets it, but clicking
    /// Home does NOT clear it (Home is a global overlay, not a context),
    /// so the project's tabs stay in the strip. None until the first
    /// project is opened.
    CurrentProject: ProjectId option
    /// "Run with parameters" modal state. None = closed. Opened by
    /// RequestRun when the chosen flow declares scalar vars.
    RunDialog: RunDialogState option
}

type Msg =
    | RefreshProjects
    | OpenProject of ProjectId
    | ActivateTab of RootTab
    | CloseTab of RootTab
    /// Close every other closable tab in the current context, keeping
    /// Home, the project root, and the given tab.
    | CloseOtherTabs of RootTab
    /// Close the closable tabs that sit to the right of the given tab in
    /// the visible strip order (later RunDetail/LiveRun chips).
    | CloseTabsToRight of RootTab
    | ActivateSubTab of ProjectId * ProjectSubTab
    | RefreshHistory of ProjectId
    | RefreshFlows of ProjectId
    | RefreshProjectInfo of ProjectId
    | OpenRunDetail of ProjectId * RunId
    /// Re-run the flow of a past run using that run's recorded params
    /// (secrets excluded — they were never stored). "Current defaults" just
    /// uses the existing RunFlow (empty overrides).
    | RerunSameParams of ProjectId * RunId
    /// Open a directory in the OS file explorer (run dir, project dir, …).
    | OpenInExplorer of path:string
    /// Open a file in the OS default app (e.g. log.txt in a text editor).
    | OpenFile of path:string
    /// Open a project in its engine's editor (UE/Unity/Godot).
    | OpenInEditor of ProjectId
    /// Clear the in-flight "Open in editor" flag for a project (timed).
    | ClearOpeningEditor of ProjectId
    /// Open a project in the configured IDE / code editor.
    | OpenInIde of ProjectId
    /// Clear the in-flight "Open in IDE" flag for a project (timed).
    | ClearOpeningIde of ProjectId
    /// Edit / save the global "Open in IDE" command template.
    | SetIdeCommandDraft of string
    | SaveIdeCommand
    /// Detect installed IDEs and offer them as presets.
    | DetectIdes
    | IdesDetected of IdeCandidate list
    /// Fill the command draft from a detected IDE preset.
    | PickIdeCandidate of command:string
    /// Godot search-paths editor / detection / pick (machine-level Godot).
    | SetGodotSearchPathsDraft of string
    | SaveGodotSearchPaths
    | DetectGodot
    | GodotDetected of DetectedEngine list
    | PickGodot of path:string
    /// Open the describe-schema Inspector for a flow step (project, flow, idx).
    | SelectStep of ProjectId * flowId:string * stepIndex:int
    | CloseInspector
    /// A step's describe schema finished loading (cache key + result).
    | StepSchemaLoaded of key:string * Result<DescribeSchema, string>
    /// Write a step param back to flows.toml (Inspector edit).
    | SetStepParam of ProjectId * flowId:string * stepIndex:int * key:string * value:TomlValue
    /// Flow Editor: add / remove / move steps in flows.toml.
    | SetAddStepDraft of ProjectId * flowId:string * string
    | AddStep of ProjectId * flowId:string * taskType:string
    | RemoveStep of ProjectId * flowId:string * stepIndex:int
    | MoveStep of ProjectId * flowId:string * stepIndex:int * delta:int
    /// Flow card expand / edit-mode toggles.
    | ToggleFlowExpanded of ProjectId * flowId:string
    | ToggleFlowEditing of ProjectId * flowId:string
    /// Settings search query.
    | SetSettingsFilter of string
    /// Watch mode: toggle a project's watched flow; timer tick polls git HEAD.
    | ToggleWatch of ProjectId * flowId:string
    | WatchPoll
    /// RunDetail log search query for a run (a find, not a filter).
    | SetRunLogFilter of ProjectId * RunId * string
    /// Move to the next / previous match of the current log search.
    | RunLogFindNext of ProjectId * RunId
    | RunLogFindPrev of ProjectId * RunId
    /// Run button entry point: opens the param dialog if the flow has
    /// scalar vars, otherwise runs immediately with no overrides.
    | RequestRun of ProjectId * flowId:string
    | RunFlow of ProjectId * flowId:string
    // Run-with-parameters dialog
    | RunDialogSetValue of name:string * value:string
    | RunDialogToggleRemember of name:string
    | RunDialogForget of name:string
    // list var editor
    | RunDialogListAdd of name:string
    | RunDialogListRemove of name:string * index:int
    | RunDialogListSetItem of name:string * index:int * value:string
    | RunDialogToggleSaveDefaults
    | RunDialogReset
    | RunDialogConfirm
    | RunDialogCancel
    /// Delete a stored secret from the keychain (Settings manager).
    | DeleteSecret of ProjectId * varName:string
    | LiveRunCompleted of LiveRunKey * Result<RunOutcome, RunFailure>
    | LiveRunProgress  of LiveRunKey * LiveProgress
    | LiveRunFailed    of LiveRunKey * exn
    | CancelLiveRun    of LiveRunKey
    // Add-Project wizard
    | ShowAddProject
    | HideAddProject
    | AddProjectSetDir    of string
    | AddProjectSetName   of string
    | AddProjectSetEngine of EngineKind
    | SubmitAddProject

/// Engine kind per project (project.toml [engine].type), for tinting the
/// Home project list. Best-effort: projects whose toml is missing/broken
/// are omitted. Recomputed whenever the project list changes. Self-contained
/// (reads p.Path directly) so it can run from `init`.
let private engineKindsFor (projects: ProjectRegistration list) : Map<ProjectId, EngineKind> =
    projects
    |> List.choose (fun (p: ProjectRegistration) ->
        let path = Path.Combine(p.Path, ".ci", "project.toml")
        if not (File.Exists path) then None
        else try Some (p.Name, (TomlConfig.loadProject path).Engine.Kind) with _ -> None)
    |> Map.ofList

let init () : Model * Cmd<Msg> =
    let projects = ProjectRegistry.load ()
    let appSettings = AppSettings.load ()
    { OpenTabs       = [ Home ]
      ActiveTab      = Home
      Projects       = projects
      ProjectSubTabs = Map.empty
      ProjectHistory = Map.empty
      ProjectFlows   = Map.empty
      ProjectInfo    = Map.empty
      ProjectEngines = engineKindsFor projects
      ProjectSecrets = Map.empty
      RunDetails     = Map.empty
      RunLogFilter   = Map.empty
      RunLogMatchIdx = Map.empty
      OpeningEditors = Set.empty
      OpeningIde     = Set.empty
      AppSettings    = appSettings
      IdeCommandDraft = appSettings.IdeCommand |> Option.defaultValue ""
      IdeCandidates  = []
      GodotSearchPathsDraft = String.concat "\n" appSettings.GodotSearchPaths
      GodotCandidates = []
      SelectedStep   = None
      StepSchemas    = Map.empty
      StepSchemasLoading = Set.empty
      AddStepDraft   = Map.empty
      ExpandedFlows  = Set.empty
      EditingFlows   = Set.empty
      SettingsFilter = ""
      Watches        = Map.empty
      LiveRuns       = Map.empty
      AddProject     = None
      CurrentProject = None
      RunDialog      = None },
    // A always-on poll timer for watch mode. It's a no-op when nothing is
    // watched; when a project is watched, WatchPoll samples its git HEAD.
    [ fun dispatch ->
        async {
            do! Async.SwitchToThreadPool ()
            while true do
                do! Async.Sleep 5000
                Dispatcher.UIThread.Post(fun () -> dispatch WatchPoll)
        }
        |> Async.Start ]

let private moveOrAppend (tab: RootTab) (tabs: RootTab list) : RootTab list =
    if List.contains tab tabs then tabs else tabs @ [ tab ]

/// Look up the active sub-tab for a project, defaulting to Flows. Used
/// by views; not used by `update` (which writes the map directly).
let projectSubTab (pid: ProjectId) (model: Model) : ProjectSubTab =
    Map.tryFind pid model.ProjectSubTabs
    |> Option.defaultValue ProjectFlows

// ─── Per-project tab scoping ─────────────────────────────────────────
// The root strip used to show every open tab in one flat row, mixing
// projects together. These helpers let the view scope the strip to the
// "current project" (the one owning the active tab) so the user only
// ever sees one project's tabs at a time. None of this lives in the
// model — it's all derived from OpenTabs/ActiveTab, so there's no extra
// state to keep in sync.

/// The project a tab belongs to, if any. Home is global (None). A
/// LiveRun tab's project is read from its live state; an entry always
/// exists while the tab is open (LiveRunCompleted only drops the entry
/// when the tab is also closed), so this is reliable for open tabs.
let tabProject (model: Model) (tab: RootTab) : ProjectId option =
    match tab with
    | Home               -> None
    | Project pid        -> Some pid
    | RunDetail (pid, _) -> Some pid
    | LiveRun key ->
        Map.tryFind key model.LiveRuns
        |> Option.map (fun s -> s.ProjectId)

/// The project context the strip is scoped to. Sticky model state, not
/// derived from the active tab — so clicking Home keeps the project's
/// tabs visible rather than wiping the strip.
let currentProject (model: Model) : ProjectId option =
    model.CurrentProject

/// Distinct open project contexts, in first-seen order across OpenTabs.
/// Drives the project selector's choice list.
let openProjects (model: Model) : ProjectId list =
    model.OpenTabs
    |> List.choose (tabProject model)
    |> List.distinct

/// Tabs the strip should show: Home always (it's a global overlay),
/// plus the tabs belonging to the current project context. With no
/// context (CurrentProject = None) only Home shows.
let visibleTabs (model: Model) : RootTab list =
    let ctx = model.CurrentProject
    model.OpenTabs
    |> List.filter (fun tab ->
        match tab with
        | Home -> true
        | _    -> tabProject model tab = ctx)

/// Stable, human-friendly serial number for a run within its project,
/// derived from chronological order: the oldest run is #1, the newest is
/// #N. `RunHistory.load` returns newest-first, so the number is
/// `count - index`. Stays stable as new runs are appended (existing runs
/// keep their number). None when the run isn't in the cached history.
let runNumber (model: Model) (pid: ProjectId) (rid: RunId) : int option =
    match Map.tryFind pid model.ProjectHistory with
    | Some entries ->
        match List.tryFindIndex (fun (e: RunHistoryEntry) -> e.RunId = rid) entries with
        | Some i -> Some (entries.Length - i)
        | None   -> None
    | None -> None

/// Flow id recorded for a run, looked up from the cached history.
let runFlowId (model: Model) (pid: ProjectId) (rid: RunId) : string option =
    match Map.tryFind pid model.ProjectHistory with
    | Some entries ->
        entries
        |> List.tryFind (fun (e: RunHistoryEntry) -> e.RunId = rid)
        |> Option.map (fun e -> e.FlowId)
    | None -> None

/// The run whose serial number is `offset` away from `rid`'s (e.g. +1 =
/// the next-newer run #N+1, -1 = the next-older #N-1). Drives the
/// prev/next navigation on a RunDetail tab. None at the ends of history
/// or when `rid` isn't in the cached list. History is newest-first, so a
/// higher number sits at a lower index → target index = i - offset.
let runByNumberOffset (model: Model) (pid: ProjectId) (rid: RunId) (offset: int) : RunId option =
    match Map.tryFind pid model.ProjectHistory with
    | Some entries ->
        match List.tryFindIndex (fun (e: RunHistoryEntry) -> e.RunId = rid) entries with
        | Some i ->
            let targetIdx = i - offset
            if targetIdx >= 0 && targetIdx < List.length entries
            then Some (List.item targetIdx entries).RunId
            else None
        | None -> None
    | None -> None

let private projectRoot
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : string option =
    projects
    |> List.tryFind (fun (p: ProjectRegistration) -> p.Name = pid)
    |> Option.map (fun p -> p.Path)

let private loadHistoryFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : RunHistoryEntry list =
    match projectRoot pid projects with
    | Some root -> RunHistory.load root
    | None      -> []

/// Reload a project's history into the cache, but only if it's already
/// cached — i.e. the Project tab is open (CloseTab drops the entry).
/// Used after a run completes so a visible History sub-tab updates
/// without manual Refresh, while avoiding orphan cache entries for
/// closed projects (which would otherwise defeat OpenProject's lazy
/// reload on the next open).
let private refreshHistoryIfOpen
        (pid: ProjectId)
        (model: Model)
        : Map<ProjectId, RunHistoryEntry list> =
    if Map.containsKey pid model.ProjectHistory then
        Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory
    else model.ProjectHistory

/// Read and classify `.ci/flows.toml` for the given project. We keep
/// the three outcomes distinct because each maps to a different UX:
/// missing → "no flows yet, here's how to add one"; error → "your
/// flows.toml has a bug, here's the message"; ok → render the list.
let private loadFlowsFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : FlowsLoad =
    match projectRoot pid projects with
    | None -> FlowsError (sprintf "Project '%s' not in registry" pid)
    | Some root ->
        let path = Path.Combine(root, ".ci", "flows.toml")
        if not (File.Exists path) then FlowsMissing
        else
            try FlowsOk (TomlConfig.loadFlows path)
            with ex -> FlowsError ex.Message

// ─── Run-with-parameters helpers ────────────────────────────────────

/// Var kinds the run dialog can render: scalars (text/pills), path/file/dir
/// (text + native picker), multiline (textarea), secret (masked + keychain),
/// and list (per-item row editor). All VarKinds are now renderable.
let isDialogVarKind (kind: VarKind) : bool =
    match kind with
    | VarKind.String | VarKind.Int | VarKind.Float
    | VarKind.Bool | VarKind.Enum _
    | VarKind.Path | VarKind.File | VarKind.Dir
    | VarKind.Multiline | VarKind.Secret
    | VarKind.List _ -> true

/// Initial editing text for a var's input: its declared default, or a
/// sensible empty/first value when no default is given.
let varDefaultText (v: FlowVar) : string =
    match v.Default with
    | Some (TString s) -> s
    | Some (TInt i)    -> string i
    | Some (TFloat f)  -> Convert.ToString(f, System.Globalization.CultureInfo.InvariantCulture)
    | Some (TBool b)   -> if b then "true" else "false"
    | Some _           -> ""   // array/table — not a scalar kind
    | None ->
        match v.Kind with
        | VarKind.Bool       -> "false"
        | VarKind.Enum (h :: _) -> h
        | _                  -> ""

/// The loaded Flow for a project's flow id, if its flows.toml is cached.
let flowById (model: Model) (pid: ProjectId) (flowId: string) : Flow option =
    match Map.tryFind pid model.ProjectFlows with
    | Some (FlowsOk flows) -> flows |> List.tryFind (fun f -> f.Id = flowId)
    | _ -> None

/// The dialog-renderable vars of a flow (declaration order), or [] if the
/// flow / its flows.toml isn't loaded or has no such vars.
let flowDialogVars (model: Model) (pid: ProjectId) (flowId: string) : FlowVar list =
    match flowById model pid flowId with
    | Some f -> f.Vars |> List.filter (fun v -> isDialogVarKind v.Kind)
    | None   -> []

/// Bool vars that some step's `when` references — surfaced as a top
/// "Toggles" section in the run dialog (they gate whole steps). The MVP
/// `when` grammar is `${vars.X}` / `!${vars.X}`, so a substring match on
/// the `${vars.X}` token is sufficient.
let whenReferencedToggles (flow: Flow) : Set<string> =
    flow.Vars
    |> List.choose (fun v -> if v.Kind = VarKind.Bool then Some v.Name else None)
    |> List.filter (fun name ->
        let token = sprintf "${vars.%s}" name
        flow.Steps |> List.exists (fun s ->
            match s.When with
            | Some w -> w.Contains(token)
            | None   -> false))
    |> Set.ofList

/// Parse a single scalar text into a typed value per `kind`. `label` is
/// used in error messages (the var name, or "<var>[<i>]" for a list item).
let private parseScalarKind (kind: VarKind) (label: string) (text: string) : Result<TomlValue, string> =
    match kind with
    | VarKind.String | VarKind.Multiline | VarKind.Path
    | VarKind.File | VarKind.Dir | VarKind.Secret | VarKind.List _ -> Ok (TString text)
    | VarKind.Bool -> Ok (TBool (text = "true"))
    | VarKind.Enum values ->
        if List.contains text values then Ok (TString text)
        else Error (sprintf "%s: '%s' is not one of %s" label text (String.concat ", " values))
    | VarKind.Int ->
        match Int64.TryParse(text.Trim(),
                             System.Globalization.NumberStyles.Integer,
                             System.Globalization.CultureInfo.InvariantCulture) with
        | true, i -> Ok (TInt i)
        | _ -> Error (sprintf "%s: '%s' is not an integer" label text)
    | VarKind.Float ->
        match Double.TryParse(text.Trim(),
                              System.Globalization.NumberStyles.Float,
                              System.Globalization.CultureInfo.InvariantCulture) with
        | true, f -> Ok (TFloat f)
        | _ -> Error (sprintf "%s: '%s' is not a number" label text)

let private parseOverrideValue (v: FlowVar) (text: string) : Result<TomlValue, string> =
    parseScalarKind v.Kind v.Name text

/// Item texts to pre-fill a list var's editor with: its declared default
/// array rendered element-by-element, or [] if no array default.
let listDefaultTexts (v: FlowVar) : string list =
    match v.Default with
    | Some (TArray xs) ->
        xs |> List.map (function
            | TString s -> s
            | TInt i    -> string i
            | TFloat f  -> Convert.ToString(f, System.Globalization.CultureInfo.InvariantCulture)
            | TBool b   -> if b then "true" else "false"
            | _         -> "")
    | _ -> []

/// Parse a list var's item texts into a TArray. Blank/whitespace rows are
/// dropped (forgiving trailing empties); the rest parse per `itemKind`.
let private parseListItems (label: string) (itemKind: VarKind) (items: string list) : Result<TomlValue, string> =
    let rec go acc = function
        | [] -> Ok (TArray (List.rev acc))
        | (item: string) :: rest ->
            if item.Trim() = "" then go acc rest
            else
                match parseScalarKind itemKind label item with
                | Error e -> Error e
                | Ok v    -> go (v :: acc) rest
    go [] items

/// Parse the non-secret edited fields, keeping only the ones that differ
/// from the declared default (so RunHistory's OverriddenKeys stays honest).
/// Secret vars are excluded here — they have no meaningful "default" diff
/// and their values come from the keychain/dialog, merged at confirm time.
/// Stops at the first parse error.
let buildOverrides (d: RunDialogState) : Result<Map<string, TomlValue>, string> =
    let addIfOverride acc (v: FlowVar) (value: TomlValue) rest go =
        let isOverride =
            match v.Default with
            | Some def -> def <> value
            | None     -> value <> TArray []   // empty list with no default → no override
        go (if isOverride then Map.add v.Name value acc else acc) rest
    let rec go acc vars =
        match vars with
        | [] -> Ok acc
        | (v: FlowVar) :: rest when v.Kind = VarKind.Secret -> go acc rest
        | (v: FlowVar) :: rest ->
            match v.Kind with
            | VarKind.List itemKind ->
                let items = Map.tryFind v.Name d.Lists |> Option.defaultValue []
                match parseListItems v.Name itemKind items with
                | Error e  -> Error e
                | Ok value -> addIfOverride acc v value rest go
            | _ ->
                let text = Map.tryFind v.Name d.Values |> Option.defaultValue (varDefaultText v)
                match parseOverrideValue v text with
                | Error e  -> Error e
                | Ok value -> addIfOverride acc v value rest go
    go Map.empty d.Vars

/// Merge secret values into a base override map for a confirmed dialog,
/// and persist any "remembered" secrets to the keychain. A non-empty
/// secret field becomes an override (kept off disk by the runner's
/// redaction); a blank one is omitted.
let applySecretOverrides
        (d: RunDialogState)
        (overrides: Map<string, TomlValue>)
        : Map<string, TomlValue> =
    d.Vars
    |> List.filter (fun v -> v.Kind = VarKind.Secret)
    |> List.fold (fun acc v ->
        match Map.tryFind v.Name d.Values with
        | Some value when value <> "" ->
            if Set.contains v.Name d.Remember then
                try Secrets.write d.ProjectId v.Name value with _ -> ()
            Map.add v.Name (TString value) acc
        | _ -> acc) overrides

/// Fields the user has changed from their declared default, as
/// (name, defaultText, currentText) for display in the dialog's "Diff
/// from defaults" section. Textual (forgiving — never errors); secret
/// vars are omitted so their value never appears. List values render as
/// "[a, b]" (blank rows dropped, matching confirm).
let dialogDiffs (d: RunDialogState) : (string * string * string) list =
    let shown (s: string) = if s = "" then "(empty)" else s
    let listText (items: string list) =
        sprintf "[%s]" (items |> List.filter (fun s -> s.Trim() <> "") |> String.concat ", ")
    d.Vars
    |> List.filter (fun v -> v.Kind <> VarKind.Secret)
    |> List.choose (fun v ->
        match v.Kind with
        | VarKind.List _ ->
            let def = listDefaultTexts v
            let cur = Map.tryFind v.Name d.Lists |> Option.defaultValue []
            let defClean = def |> List.filter (fun s -> s.Trim() <> "")
            let curClean = cur |> List.filter (fun s -> s.Trim() <> "")
            if defClean <> curClean then Some (v.Name, listText def, listText cur) else None
        | _ ->
            let def = varDefaultText v
            let cur = Map.tryFind v.Name d.Values |> Option.defaultValue def
            if cur <> def then Some (v.Name, shown def, shown cur) else None)

/// Resolve the Tasks SDK assembly + builtin tasks dir from the host
/// process layout. Same defaults the CLI uses; works here because the
/// GUI project-references Takatora.Tasks + Takatora.Tasks.Builtin, so
/// Tasks.dll + builtin-tasks/ get copied next to the GUI executable.
let private sdkAssemblyPath () =
    Path.Combine(AppContext.BaseDirectory, "Takatora.Tasks.dll")

let private builtinTasksDir () =
    Path.Combine(AppContext.BaseDirectory, "builtin-tasks")

let private userTasksDir () =
    Path.Combine(
        System.Environment.GetFolderPath System.Environment.SpecialFolder.ApplicationData,
        "Takatora", "tasks")

/// Resolve a step's task .fsx (+ its source: project/user/builtin) the same
/// way the runner does. Used by the describe-driven step Inspector.
let resolveStepTask (projectRoot: string) (taskType: string) : ResolvedTask option =
    TaskResolver.resolve projectRoot (Some (userTasksDir ())) (builtinTasksDir ()) taskType

/// Describe-schema cache key: task path + its mtime, so editing the .fsx
/// invalidates the cached schema.
let stepSchemaKey (path: string) : string =
    let ticks = try (File.GetLastWriteTimeUtc path).Ticks with _ -> 0L
    sprintf "%s|%d" path ticks

/// Apply machine-level engine settings to a project's [engine]. For Godot
/// (which has no canonical install), inject the chosen GodotPath as
/// engine_path when the project doesn't set one — so engine resolution /
/// "Open in editor" work without a per-project, committed path.
let effectiveEngine (settings: AppSettings) (engine: Engine) : Engine =
    match engine.Kind with
    | EngineKind.Godot when (engine.EnginePath |> Option.forall System.String.IsNullOrWhiteSpace) ->
        match settings.GodotPath with
        | Some p when not (System.String.IsNullOrWhiteSpace p) -> { engine with EnginePath = Some p }
        | _ -> engine
    | _ -> engine

/// Split a command line into (exe, args): a leading quoted path, else the
/// first whitespace-delimited token, is the exe; the rest is the args string.
let splitCommand (cmd: string) : string * string =
    let s = cmd.Trim()
    if s.StartsWith("\"") then
        match s.IndexOf('"', 1) with
        | q when q > 0 -> s.Substring(1, q - 1), s.Substring(q + 1).TrimStart()
        | _ -> s.Trim('"'), ""
    else
        match s.IndexOf(' ') with
        | sp when sp > 0 -> s.Substring(0, sp), s.Substring(sp + 1).TrimStart()
        | _ -> s, ""

/// Split the Godot search-paths editor text (one dir per line) into a list.
let parseSearchPaths (text: string) : string list =
    text.Split([| '\n'; '\r' |])
    |> Array.map (fun s -> s.Trim())
    |> Array.filter (fun s -> s <> "")
    |> Array.toList

// ─── Live run tailing ───────────────────────────────────────────────
//
// The runner writes events.ndjson + log.txt under
// `<root>/.ci/runs/<runId>/` while it executes (each step appends as it
// goes). The GUI never learns the runId — Run.execute generates it
// internally — so we detect the new run dir by diffing `.ci/runs/`
// against a snapshot captured the instant before the run starts, then
// poll that dir on a background thread, marshaling snapshots to the UI.

/// Run-dir names present under `<root>/.ci/runs/` right now. Captured at
/// launch so the poller can spot the one this run creates.
let private existingRunDirs (root: string) : Set<string> =
    let runsDir = Path.Combine(root, ".ci", "runs")
    if Directory.Exists runsDir then
        Directory.GetDirectories runsDir
        |> Array.map Path.GetFileName
        |> Set.ofArray
    else Set.empty

/// The newest run dir under `<root>/.ci/runs/` not present in `before`.
/// Run ids sort lexicographically by time, so the max name is the latest.
let private findNewRunDir (root: string) (before: Set<string>) : string option =
    let runsDir = Path.Combine(root, ".ci", "runs")
    if not (Directory.Exists runsDir) then None
    else
        Directory.GetDirectories runsDir
        |> Array.map Path.GetFileName
        |> Array.filter (fun n -> not (Set.contains n before))
        |> Array.sortDescending
        |> Array.tryHead
        |> Option.map (fun n -> Path.Combine(runsDir, n))

/// Read all non-empty lines from a file the runner may be appending to
/// concurrently. FileShare.ReadWrite avoids fighting the writer's lock.
let private readSharedLines (path: string) : string list =
    try
        if not (File.Exists path) then []
        else
            use fs =
                new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)
            use sr = new StreamReader(fs)
            sr.ReadToEnd().Split('\n')
            |> Array.choose (fun l ->
                let t = l.TrimEnd('\r')
                if t.Trim() = "" then None else Some t)
            |> Array.toList
    with _ -> []

let private maxLogTail = 300

/// Parse a run dir's events.ndjson + log.txt into a LiveProgress
/// snapshot. Tolerant of partial/garbled trailing lines (the writer may
/// be mid-append) — bad lines are skipped rather than failing the tick.
let private readProgress (runDir: string) : LiveProgress =
    let events = readSharedLines (Path.Combine(runDir, "events.ndjson"))
    // Ordered, de-duplicated step list keyed by step_id.
    let steps = System.Collections.Generic.List<LiveStep>()
    let indexOf (id: string) =
        let mutable found = -1
        for i in 0 .. steps.Count - 1 do
            if steps.[i].Id = id then found <- i
        found
    let upsert (id: string) (typ: string) (status: LiveStepStatus) (dur: float) =
        let i = indexOf id
        let step = { Id = id; Type = typ; Status = status; DurationSec = dur }
        if i < 0 then steps.Add step else steps.[i] <- step
    let mutable ended = false
    for line in events do
        try
            use doc = JsonDocument.Parse(line)
            let root = doc.RootElement
            let str (name: string) =
                match root.TryGetProperty name with
                | true, v when v.ValueKind = JsonValueKind.String -> v.GetString()
                | _ -> ""
            let num (name: string) =
                match root.TryGetProperty name with
                | true, v when v.ValueKind = JsonValueKind.Number -> v.GetDouble()
                | _ -> 0.0
            match str "kind" with
            | "step.start" -> upsert (str "step_id") (str "type") StepRunning 0.0
            | "step.end" ->
                let status =
                    match str "status" with
                    | "success"   -> StepOk
                    | "cancelled" -> StepCancelled
                    | _           -> StepFailed
                upsert (str "step_id") (str "type") status (num "duration_sec")
            | "step.skip" -> upsert (str "step_id") (str "type") StepSkipped 0.0
            | "run.end"   -> ended <- true
            | _ -> ()
        with _ -> ()
    let logTail =
        let all = readSharedLines (Path.Combine(runDir, "log.txt"))
        if List.length all > maxLogTail then
            all |> List.skip (List.length all - maxLogTail)
        else all
    { RunDir = Some runDir; Steps = List.ofSeq steps; LogTail = logTail; Ended = ended }

/// Same shape as `loadFlowsFor` but for `.ci/project.toml`.
let private loadProjectInfoFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : ProjectInfoLoad =
    match projectRoot pid projects with
    | None -> ProjectInfoError (sprintf "Project '%s' not in registry" pid)
    | Some root ->
        let path = Path.Combine(root, ".ci", "project.toml")
        if not (File.Exists path) then ProjectInfoMissing
        else
            try ProjectInfoOk (TomlConfig.loadProject path)
            with ex -> ProjectInfoError ex.Message

/// Tabs that *bulk* close operations may remove: closable run tabs only.
/// Home and the project root are anchors — bulk ops never touch them.
let bulkClosable (tab: RootTab) : bool =
    match tab with
    | Home | Project _        -> false
    | RunDetail _ | LiveRun _ -> true

/// Remove `toClose` from the model in one pass: drop the per-tab caches,
/// recompute the active tab within the current context (keeping the same
/// strip position where possible), and fall back to Home/no-context if
/// the current project has no tabs left. Home is never closed. Shared by
/// CloseTab and the bulk close handlers so they all reassign consistently.
let closeTabs (toClose: RootTab list) (model: Model) : Model * Cmd<Msg> =
    let toCloseSet =
        toClose |> List.filter (function Home -> false | _ -> true) |> Set.ofList
    if Set.isEmpty toCloseSet then model, Cmd.none
    else
        let cleanCaches (m: Model) (t: RootTab) : Model =
            match t with
            | Project pid ->
                { m with
                    ProjectSubTabs = Map.remove pid m.ProjectSubTabs
                    ProjectHistory = Map.remove pid m.ProjectHistory
                    ProjectFlows   = Map.remove pid m.ProjectFlows
                    ProjectInfo    = Map.remove pid m.ProjectInfo }
            | RunDetail (pid, rid) -> { m with RunDetails = Map.remove (pid, rid) m.RunDetails }
            | LiveRun _ | Home     -> m
        // Pick the next active tab within the strip the user is looking at,
        // keeping the same slot index where possible (survivors always
        // include Home). LiveRuns entries are intentionally NOT dropped for
        // still-Pending tabs — LiveRunCompleted needs them to find the pid.
        let oldVisible = visibleTabs model
        let newActive =
            if not (Set.contains model.ActiveTab toCloseSet) then model.ActiveTab
            else
                match List.tryFindIndex ((=) model.ActiveTab) oldVisible with
                | None -> Home
                | Some idx ->
                    let survivors =
                        oldVisible |> List.filter (fun t -> not (Set.contains t toCloseSet))
                    if List.isEmpty survivors then Home
                    elif idx < List.length survivors then List.item idx survivors
                    else List.last survivors
        let cleaned = Set.fold cleanCaches model toCloseSet
        let intermediate =
            { cleaned with
                OpenTabs  = model.OpenTabs |> List.filter (fun t -> not (Set.contains t toCloseSet))
                ActiveTab = newActive }
        let contextStillOpen =
            match model.CurrentProject with
            | Some pid -> openProjects intermediate |> List.contains pid
            | None     -> false
        if contextStillOpen then intermediate, Cmd.none
        else { intermediate with ActiveTab = Home; CurrentProject = None }, Cmd.none

/// Kick off an in-process flow run with the given var overrides: spin up
/// a LiveRun tab immediately, then schedule Run.execute + the tail poller
/// on the thread pool (marshaling results back via Dispatcher.UIThread).
/// Shared by the no-vars Run path and the param-dialog confirm.
let private startRun
        (pid: ProjectId)
        (flowId: string)
        (overrides: Map<string, TomlValue>)
        (model: Model)
        : Model * Cmd<Msg> =
    match projectRoot pid model.Projects with
    | None -> model, Cmd.none
    | Some root ->
        let key = Guid.NewGuid()
        let tab = LiveRun key
        let liveState = {
            ProjectId = pid
            FlowId    = flowId
            StartedAt = DateTimeOffset.UtcNow
            Phase     = LivePending
            Progress  = LiveProgress.empty
            CancelRequested = false
        }
        // Snapshot the runs dir before launching so the poller can
        // identify the dir this run is about to create.
        let runsBefore = existingRunDirs root
        let opts : Run.Options = {
            WorkingDir       = root
            FlowId           = flowId
            VarOverrides     = overrides
            SdkAssemblyPath  = sdkAssemblyPath ()
            BuiltinTasksDir  = builtinTasksDir ()
            UserTasksDir     = None
        }
        // Run on the thread pool, then marshal the result message
        // back onto the Avalonia UI thread before dispatching.
        //
        // We deliberately do NOT use Cmd.OfAsync.either here: in
        // Elmish, the dispatch loop runs `setState` (→ FuncUI's
        // host.Update → Avalonia view rebuild) on whatever thread
        // calls `dispatch`. FuncUI.Elmish 1.5.1's withHost does not
        // marshal, so dispatching from the thread-pool thread would
        // rebuild the view off the UI thread and crash the whole
        // app. Dispatcher.UIThread.Post guarantees the dispatch —
        // and thus the re-render — happens on the UI thread.
        let runCmd : Cmd<Msg> =
            [ fun dispatch ->
                async {
                    do! Async.SwitchToThreadPool ()
                    let msg =
                        try LiveRunCompleted (key, Run.execute opts)
                        with ex -> LiveRunFailed (key, ex)
                    Dispatcher.UIThread.Post(fun () -> dispatch msg)
                }
                |> Async.Start ]
        // Independent tail poller. Reads the run's events/log files
        // (which Run.execute appends to live) every ~300ms and posts
        // a LiveRunProgress snapshot to the UI thread, until it sees
        // a run.end event or hits the safety cap. Runs concurrently
        // with the executor above; both are UI-thread-safe via Post.
        let pollCmd : Cmd<Msg> =
            [ fun dispatch ->
                async {
                    do! Async.SwitchToThreadPool ()
                    let mutable runDir = None
                    let mutable finished = false
                    let mutable ticks = 0
                    // Cap ~ 1 hour at 300ms cadence; a stuck run won't
                    // poll forever if run.end is somehow never written.
                    while not finished && ticks < 12000 do
                        ticks <- ticks + 1
                        if Option.isNone runDir then
                            runDir <- findNewRunDir root runsBefore
                        match runDir with
                        | Some dir ->
                            let progress = readProgress dir
                            Dispatcher.UIThread.Post(fun () ->
                                dispatch (LiveRunProgress (key, progress)))
                            if progress.Ended then finished <- true
                        | None -> ()
                        if not finished then do! Async.Sleep 300
                }
                |> Async.Start ]
        { model with
            OpenTabs       = moveOrAppend tab model.OpenTabs
            ActiveTab      = tab
            CurrentProject = Some pid
            LiveRuns       = Map.add key liveState model.LiveRuns },
        Cmd.batch [ runCmd; pollCmd ]

/// Apply a surgical edit to a project's flows.toml, then reload the flows
/// cache. `clearSelection` drops the Inspector (used when step indices shift).
/// No-op (returns the model unchanged) if the project/file/edit doesn't apply.
let private editFlowsFile
        (pid: ProjectId) (model: Model) (clearSelection: bool)
        (edit: string -> string * bool)
        : Model =
    match projectRoot pid model.Projects with
    | None -> model
    | Some root ->
        let flowsPath = Path.Combine(root, ".ci", "flows.toml")
        try
            let text = File.ReadAllText flowsPath
            let newText, ok = edit text
            if not ok then model
            else
                File.WriteAllText(flowsPath, newText)
                let m =
                    { model with
                        ProjectFlows = Map.add pid (loadFlowsFor pid model.Projects) model.ProjectFlows }
                if clearSelection then { m with SelectedStep = None } else m
        with _ -> model

/// Is a run for this project still in flight? Watch mode coalesces on this
/// (it won't kick off a second watched run while one is going).
let private hasActiveWatchRun (pid: ProjectId) (model: Model) : bool =
    model.LiveRuns
    |> Map.exists (fun _ s -> s.ProjectId = pid && (match s.Phase with LivePending -> true | _ -> false))

let update (msg: Msg) (model: Model) : Model * Cmd<Msg> =
    match msg with
    | RefreshProjects ->
        let projects = ProjectRegistry.load ()
        { model with Projects = projects; ProjectEngines = engineKindsFor projects }, Cmd.none
    | OpenProject pid ->
        let tab = Project pid
        let history =
            if Map.containsKey pid model.ProjectHistory then model.ProjectHistory
            else Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory
        let flows =
            if Map.containsKey pid model.ProjectFlows then model.ProjectFlows
            else Map.add pid (loadFlowsFor pid model.Projects) model.ProjectFlows
        let info =
            if Map.containsKey pid model.ProjectInfo then model.ProjectInfo
            else Map.add pid (loadProjectInfoFor pid model.Projects) model.ProjectInfo
        let secrets =
            if Map.containsKey pid model.ProjectSecrets then model.ProjectSecrets
            else Map.add pid (Secrets.listForProject pid) model.ProjectSecrets
        { model with
            OpenTabs       = moveOrAppend tab model.OpenTabs
            ActiveTab      = tab
            CurrentProject = Some pid
            ProjectHistory = history
            ProjectFlows   = flows
            ProjectInfo    = info
            ProjectSecrets = secrets },
        Cmd.none
    | ActivateTab tab ->
        if List.contains tab model.OpenTabs then
            // Activating a project-owning tab switches the context to it;
            // activating Home leaves CurrentProject sticky so the strip
            // keeps showing the project's tabs.
            let current =
                match tabProject model tab with
                | Some pid -> Some pid
                | None     -> model.CurrentProject
            { model with ActiveTab = tab; CurrentProject = current }, Cmd.none
        else model, Cmd.none
    | CloseTab Home -> model, Cmd.none  // Home is not closable.
    | CloseTab tab -> closeTabs [ tab ] model
    | CloseOtherTabs keep ->
        // Close every other run tab in this context; keep Home, the project
        // root, and `keep` (which also becomes the active tab).
        let toClose =
            visibleTabs model
            |> List.filter (fun t -> bulkClosable t && t <> keep)
        let m, cmd = closeTabs toClose model
        let current =
            match tabProject m keep with
            | Some pid -> Some pid
            | None     -> m.CurrentProject
        { m with ActiveTab = keep; CurrentProject = current }, cmd
    | CloseTabsToRight tab ->
        // Close the closable tabs that come after `tab` in the visible strip.
        let vis = visibleTabs model
        match List.tryFindIndex ((=) tab) vis with
        | None -> model, Cmd.none
        | Some idx ->
            let toClose =
                vis
                |> List.indexed
                |> List.choose (fun (i, t) ->
                    if i > idx && bulkClosable t then Some t else None)
            closeTabs toClose model
    | ActivateSubTab (pid, sub) ->
        // Entering Settings re-reads the keychain so a secret saved via the
        // run dialog (or removed in the OS) shows up without a manual refresh.
        let secrets =
            match sub with
            | ProjectSettings -> Map.add pid (Secrets.listForProject pid) model.ProjectSecrets
            | _               -> model.ProjectSecrets
        { model with
            ProjectSubTabs = Map.add pid sub model.ProjectSubTabs
            ProjectSecrets = secrets },
        Cmd.none
    | RefreshHistory pid ->
        { model with
            ProjectHistory = Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory },
        Cmd.none
    | RefreshFlows pid ->
        { model with
            ProjectFlows = Map.add pid (loadFlowsFor pid model.Projects) model.ProjectFlows },
        Cmd.none
    | RefreshProjectInfo pid ->
        { model with
            ProjectInfo    = Map.add pid (loadProjectInfoFor pid model.Projects) model.ProjectInfo
            ProjectSecrets = Map.add pid (Secrets.listForProject pid) model.ProjectSecrets },
        Cmd.none
    | OpenRunDetail (pid, runId) ->
        let tab = RunDetail (pid, runId)
        let key = pid, runId
        let details =
            if Map.containsKey key model.RunDetails then model.RunDetails
            else
                match projectRoot pid model.Projects with
                | None -> model.RunDetails
                | Some root ->
                    match RunHistory.findRun root runId with
                    | Some (entry, steps) ->
                        let outputs = RunHistory.runOutputs root runId
                        let logLines = RunHistory.readLog root runId 50000
                        Map.add key (entry, steps, outputs, logLines) model.RunDetails
                    | None -> model.RunDetails
        { model with
            OpenTabs       = moveOrAppend tab model.OpenTabs
            ActiveTab      = tab
            CurrentProject = Some pid
            RunDetails     = details },
        Cmd.none
    | RequestRun (pid, flowId) ->
        // Run button entry point. If the flow declares scalar vars, open
        // the param dialog (pre-filled with declared defaults); otherwise
        // there's nothing to fill in, so run straight away.
        match flowDialogVars model pid flowId with
        | [] -> startRun pid flowId Map.empty model
        | vars ->
            // Secret fields pre-fill from the keychain (shown masked); a
            // stored secret defaults to "remembered" so a re-run keeps it.
            let stored =
                vars
                |> List.filter (fun v -> v.Kind = VarKind.Secret && Secrets.exists pid v.Name)
                |> List.map (fun v -> v.Name)
                |> Set.ofList
            let values =
                vars
                |> List.map (fun v ->
                    match v.Kind with
                    | VarKind.Secret -> v.Name, (Secrets.read pid v.Name |> Option.defaultValue "")
                    | _              -> v.Name, varDefaultText v)
                |> Map.ofList
            let lists =
                vars
                |> List.choose (fun v ->
                    match v.Kind with
                    | VarKind.List _ -> Some (v.Name, listDefaultTexts v)
                    | _              -> None)
                |> Map.ofList
            let toggles =
                match flowById model pid flowId with
                | Some f -> whenReferencedToggles f
                | None   -> Set.empty
            { model with
                RunDialog =
                    Some { ProjectId = pid
                           FlowId    = flowId
                           Vars      = vars
                           Values    = values
                           Lists     = lists
                           Toggles   = toggles
                           SaveDefaults = false
                           Remember  = stored
                           Stored    = stored
                           Error     = None } },
            Cmd.none
    | RunDialogSetValue (name, value) ->
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            { model with
                RunDialog =
                    Some { d with
                            Values = Map.add name value d.Values
                            Error  = None } },
            Cmd.none
    | RunDialogToggleRemember name ->
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            let remember =
                if Set.contains name d.Remember then Set.remove name d.Remember
                else Set.add name d.Remember
            { model with RunDialog = Some { d with Remember = remember } }, Cmd.none
    | RunDialogForget name ->
        // Drop the stored keychain entry and clear the field.
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            Secrets.delete d.ProjectId name |> ignore
            { model with
                RunDialog =
                    Some { d with
                            Values   = Map.add name "" d.Values
                            Stored   = Set.remove name d.Stored
                            Remember = Set.remove name d.Remember } },
            Cmd.none
    | RunDialogListAdd name ->
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            let cur = Map.tryFind name d.Lists |> Option.defaultValue []
            { model with RunDialog = Some { d with Lists = Map.add name (cur @ [ "" ]) d.Lists; Error = None } },
            Cmd.none
    | RunDialogListRemove (name, index) ->
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            let cur = Map.tryFind name d.Lists |> Option.defaultValue []
            let next = cur |> List.indexed |> List.choose (fun (i, x) -> if i = index then None else Some x)
            { model with RunDialog = Some { d with Lists = Map.add name next d.Lists; Error = None } },
            Cmd.none
    | RunDialogListSetItem (name, index, value) ->
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            let cur = Map.tryFind name d.Lists |> Option.defaultValue []
            let next = cur |> List.mapi (fun i x -> if i = index then value else x)
            { model with RunDialog = Some { d with Lists = Map.add name next d.Lists; Error = None } },
            Cmd.none
    | RunDialogToggleSaveDefaults ->
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d -> { model with RunDialog = Some { d with SaveDefaults = not d.SaveDefaults } }, Cmd.none
    | RunDialogReset ->
        // Restore every field to its declared default (secrets re-read the
        // keychain so a stored value reappears; lists reset to their array).
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            let values =
                d.Vars
                |> List.map (fun v ->
                    match v.Kind with
                    | VarKind.Secret -> v.Name, (Secrets.read d.ProjectId v.Name |> Option.defaultValue "")
                    | _              -> v.Name, varDefaultText v)
                |> Map.ofList
            let lists =
                d.Vars
                |> List.choose (fun v ->
                    match v.Kind with
                    | VarKind.List _ -> Some (v.Name, listDefaultTexts v)
                    | _              -> None)
                |> Map.ofList
            { model with RunDialog = Some { d with Values = values; Lists = lists; Error = None } },
            Cmd.none
    | RunDialogCancel ->
        { model with RunDialog = None }, Cmd.none
    | RunDialogConfirm ->
        match model.RunDialog with
        | None -> model, Cmd.none
        | Some d ->
            match buildOverrides d with
            | Error msg ->
                { model with RunDialog = Some { d with Error = Some msg } }, Cmd.none
            | Ok overrides ->
                // Merge in secret values (and persist any "remembered" ones
                // to the keychain).
                let overrides = applySecretOverrides d overrides
                let run model = startRun d.ProjectId d.FlowId overrides { model with RunDialog = None }
                if not d.SaveDefaults then run model
                else
                    // Write the changed (non-secret) values back to flows.toml
                    // as the new defaults, then run. Secrets are excluded —
                    // overrides already omits them. If any var can't be saved,
                    // keep the dialog open and report it (nothing is written).
                    let changed =
                        overrides
                        |> Map.toList
                        |> List.choose (fun (n, v) ->
                            d.Vars
                            |> List.tryFind (fun fv -> fv.Name = n && fv.Kind <> VarKind.Secret)
                            |> Option.map (fun fv -> fv, v))
                    match projectRoot d.ProjectId model.Projects with
                    | None -> run model   // unregistered/transient — just run
                    | Some root ->
                        let flowsPath = Path.Combine(root, ".ci", "flows.toml")
                        try
                            let text = File.ReadAllText flowsPath
                            let newText, skipped = FlowsEdit.setVarDefaults text d.FlowId changed
                            if not (List.isEmpty skipped) then
                                { model with
                                    RunDialog =
                                        Some { d with
                                                Error = Some (sprintf "Couldn't save defaults for: %s — edit flows.toml by hand, or uncheck Save."
                                                                (String.concat ", " skipped)) } },
                                Cmd.none
                            else
                                File.WriteAllText(flowsPath, newText)
                                // Reload the flows cache so the new defaults show next time.
                                let flows = Map.add d.ProjectId (loadFlowsFor d.ProjectId model.Projects) model.ProjectFlows
                                run { model with ProjectFlows = flows }
                        with ex ->
                            { model with RunDialog = Some { d with Error = Some (sprintf "Save failed: %s" ex.Message) } },
                            Cmd.none
    | RunFlow (pid, flowId) ->
        // Direct run with no overrides (used internally / by RequestRun
        // for flows that declare no scalar vars).
        startRun pid flowId Map.empty model
    | RerunSameParams (pid, runId) ->
        // Re-run the flow with the past run's recorded params. The manifest
        // only ever stored "***" for secrets, so we must NOT replay those
        // masked values — instead re-source each secret from the keychain
        // (omitted if not stored). Non-secret params come straight from the
        // recorded run.
        match Map.tryFind (pid, runId) model.RunDetails with
        | None -> model, Cmd.none
        | Some (entry, _, _, _) ->
            let secretNames =
                match flowById model pid entry.FlowId with
                | Some f -> f.Vars |> List.choose (fun v -> if v.Kind = VarKind.Secret then Some v.Name else None) |> Set.ofList
                | None   -> Set.empty
            let baseOverrides = entry.Params |> Map.filter (fun k _ -> not (Set.contains k secretNames))
            let overrides =
                secretNames
                |> Set.fold (fun acc name ->
                    match Secrets.read pid name with
                    | Some v -> Map.add name (TString v) acc
                    | None   -> acc) baseOverrides
            startRun pid entry.FlowId overrides model
    | OpenInExplorer path ->
        // Open the directory in the OS file explorer. Best-effort; a missing
        // dir or a headless host just no-ops. Normalize separators first —
        // explorer.exe opens the default folder (Documents) for a path with
        // mixed `/` and `\` (e.g. an archive_dir like "Package/Windows"
        // joined onto a Windows prefix).
        (try
            let normalized = try Path.GetFullPath path with _ -> path
            if Directory.Exists normalized then
                let psi = System.Diagnostics.ProcessStartInfo("explorer.exe")
                psi.ArgumentList.Add(normalized)
                System.Diagnostics.Process.Start(psi) |> ignore
         with _ -> ())
        model, Cmd.none
    | OpenFile path ->
        // Open a file in the OS default app (UseShellExecute lets the shell
        // pick the editor for .txt). Best-effort.
        (try
            let normalized = try Path.GetFullPath path with _ -> path
            if File.Exists normalized then
                let psi = System.Diagnostics.ProcessStartInfo(normalized)
                psi.UseShellExecute <- true
                System.Diagnostics.Process.Start(psi) |> ignore
         with _ -> ())
        model, Cmd.none
    | OpenInEditor pid when Set.contains pid model.OpeningEditors ->
        // Already launching — ignore the repeat click (no second window).
        model, Cmd.none
    | OpenInEditor pid ->
        // Launch the project's engine editor. Resolution (which exe + args,
        // shell-delegate or not) lives in Core; the view only enables this
        // when resolution succeeds, so a failure here is best-effort silent.
        let launched =
            match projectRoot pid model.Projects, Map.tryFind pid model.ProjectInfo with
            | Some root, Some (ProjectInfoOk project) ->
                match Engines.resolveEditorLaunch (effectiveEngine model.AppSettings project.Engine) root with
                | Ok launch ->
                    try
                        let psi =
                            if launch.UseShell then
                                // Dispatch through Explorer so the file opens with
                                // its registered handler exactly as a double-click
                                // would. Our own ShellExecute spawns the handler
                                // (UE's UnrealVersionSelector / Rider) as a child of
                                // this process, which it handles poorly (.port
                                // collisions, "already running" even when not).
                                let p = System.Diagnostics.ProcessStartInfo("explorer.exe")
                                p.ArgumentList.Add(launch.Exe)
                                p
                            else
                                let p = System.Diagnostics.ProcessStartInfo(launch.Exe)
                                p.UseShellExecute <- false
                                for a in launch.Args do p.ArgumentList.Add(a)
                                p.WorkingDirectory <- root
                                p
                        System.Diagnostics.Process.Start(psi) |> ignore
                        true
                    with _ -> false
                | Error _ -> false
            | _ -> false
        if not launched then model, Cmd.none
        else
            // Mark in-flight and re-enable after a cooldown — long enough to
            // cover a cold editor/IDE start, so repeat clicks in that window
            // don't queue extra launches.
            let reEnable : Cmd<Msg> =
                [ fun dispatch ->
                    async {
                        do! Async.SwitchToThreadPool ()
                        do! Async.Sleep 12000
                        Dispatcher.UIThread.Post(fun () -> dispatch (ClearOpeningEditor pid))
                    }
                    |> Async.Start ]
            { model with OpeningEditors = Set.add pid model.OpeningEditors }, reEnable
    | ClearOpeningEditor pid ->
        { model with OpeningEditors = Set.remove pid model.OpeningEditors }, Cmd.none
    | OpenInIde pid when Set.contains pid model.OpeningIde ->
        model, Cmd.none
    | OpenInIde pid ->
        // Launch the IDE the SAME way the OS shell does when the user starts it
        // by hand — ProcessStartInfo with UseShellExecute=true (ShellExecuteEx).
        // Launching it as our child via `cmd` ran it in a non-interactive
        // context, which broke single-instance IDEs (Rider's DirectoryLock /
        // OneDrive-backed .port couldn't be activated/hydrated — yet a manual
        // launch worked). Shell-executing the resolved exe + args matches the
        // manual path.
        let launched =
            match projectRoot pid model.Projects, Map.tryFind pid model.ProjectInfo with
            | Some root, Some (ProjectInfoOk project) ->
                match model.AppSettings.IdeCommand with
                | Some template ->
                    match Engines.resolveIdeCommand project.Engine root template with
                    | Ok cmdLine ->
                        try
                            let exe, args = splitCommand cmdLine
                            let psi = System.Diagnostics.ProcessStartInfo(exe)
                            psi.Arguments <- args
                            psi.UseShellExecute <- true
                            psi.WorkingDirectory <- root
                            System.Diagnostics.Process.Start(psi) |> ignore
                            true
                        with _ -> false
                    | Error _ -> false
                | None -> false
            | _ -> false
        if not launched then model, Cmd.none
        else
            let reEnable : Cmd<Msg> =
                [ fun dispatch ->
                    async {
                        do! Async.SwitchToThreadPool ()
                        do! Async.Sleep 12000
                        Dispatcher.UIThread.Post(fun () -> dispatch (ClearOpeningIde pid))
                    }
                    |> Async.Start ]
            { model with OpeningIde = Set.add pid model.OpeningIde }, reEnable
    | ClearOpeningIde pid ->
        { model with OpeningIde = Set.remove pid model.OpeningIde }, Cmd.none
    | SetIdeCommandDraft text ->
        { model with IdeCommandDraft = text }, Cmd.none
    | SaveIdeCommand ->
        // Persist the (trimmed) draft to machine-local settings; blank clears it.
        let trimmed = model.IdeCommandDraft.Trim()
        let ideCommand = if trimmed = "" then None else Some trimmed
        let settings = { model.AppSettings with IdeCommand = ideCommand }
        (try AppSettings.save settings with _ -> ())
        { model with AppSettings = settings; IdeCommandDraft = defaultArg ideCommand "" }, Cmd.none
    | DetectIdes ->
        // Detection spawns vswhere + scans dirs — do it off the UI thread.
        let cmd : Cmd<Msg> =
            [ fun dispatch ->
                async {
                    do! Async.SwitchToThreadPool ()
                    let found = try Ides.detect () with _ -> []
                    Dispatcher.UIThread.Post(fun () -> dispatch (IdesDetected found))
                }
                |> Async.Start ]
        model, cmd
    | IdesDetected candidates ->
        { model with IdeCandidates = candidates }, Cmd.none
    | PickIdeCandidate command ->
        { model with IdeCommandDraft = command }, Cmd.none
    | SetGodotSearchPathsDraft text ->
        { model with GodotSearchPathsDraft = text }, Cmd.none
    | SaveGodotSearchPaths ->
        let paths = parseSearchPaths model.GodotSearchPathsDraft
        let settings = { model.AppSettings with GodotSearchPaths = paths }
        (try AppSettings.save settings with _ -> ())
        { model with AppSettings = settings }, Cmd.none
    | DetectGodot ->
        // Scan PATH + the (draft) search paths off the UI thread.
        let paths = parseSearchPaths model.GodotSearchPathsDraft
        let cmd : Cmd<Msg> =
            [ fun dispatch ->
                async {
                    do! Async.SwitchToThreadPool ()
                    let found = try Engines.godotCandidates paths with _ -> []
                    Dispatcher.UIThread.Post(fun () -> dispatch (GodotDetected found))
                }
                |> Async.Start ]
        model, cmd
    | GodotDetected candidates ->
        { model with GodotCandidates = candidates }, Cmd.none
    | PickGodot path ->
        // Persist the chosen Godot as the machine-level engine.
        let settings = { model.AppSettings with GodotPath = Some path }
        (try AppSettings.save settings with _ -> ())
        { model with AppSettings = settings }, Cmd.none
    | CloseInspector ->
        { model with SelectedStep = None }, Cmd.none
    | SetStepParam (pid, flowId, idx, key, value) ->
        editFlowsFile pid model false (fun text -> FlowsEdit.setStepParam text flowId idx key value), Cmd.none
    | SetAddStepDraft (pid, flowId, text) ->
        { model with AddStepDraft = Map.add (pid, flowId) text model.AddStepDraft }, Cmd.none
    | AddStep (pid, flowId, taskType) ->
        let t = taskType.Trim()
        if t = "" then model, Cmd.none
        else
            let m = editFlowsFile pid model false (fun text -> FlowsEdit.addStep text flowId t)
            { m with AddStepDraft = Map.remove (pid, flowId) m.AddStepDraft }, Cmd.none
    | RemoveStep (pid, flowId, idx) ->
        // Indices shift after a remove → drop the Inspector selection.
        editFlowsFile pid model true (fun text -> FlowsEdit.removeStep text flowId idx), Cmd.none
    | MoveStep (pid, flowId, idx, delta) ->
        editFlowsFile pid model true (fun text -> FlowsEdit.moveStep text flowId idx delta), Cmd.none
    | ToggleFlowExpanded (pid, flowId) ->
        let key = (pid, flowId)
        if Set.contains key model.ExpandedFlows then
            // Collapsing also leaves edit mode.
            { model with
                ExpandedFlows = Set.remove key model.ExpandedFlows
                EditingFlows  = Set.remove key model.EditingFlows }, Cmd.none
        else { model with ExpandedFlows = Set.add key model.ExpandedFlows }, Cmd.none
    | ToggleFlowEditing (pid, flowId) ->
        let key = (pid, flowId)
        if Set.contains key model.EditingFlows then
            { model with EditingFlows = Set.remove key model.EditingFlows }, Cmd.none
        else
            // Entering edit mode implies the card is expanded.
            { model with
                EditingFlows  = Set.add key model.EditingFlows
                ExpandedFlows = Set.add key model.ExpandedFlows }, Cmd.none
    | SetSettingsFilter text ->
        { model with SettingsFilter = text }, Cmd.none
    | ToggleWatch (pid, flowId) ->
        match Map.tryFind pid model.Watches with
        | Some w when w.FlowId = flowId ->
            { model with Watches = Map.remove pid model.Watches }, Cmd.none
        | _ ->
            // Start from the current commit so we only fire on NEW commits.
            let head = projectRoot pid model.Projects |> Option.bind Watch.gitHead
            { model with Watches = Map.add pid { FlowId = flowId; LastHead = head } model.Watches }, Cmd.none
    | WatchPoll ->
        if Map.isEmpty model.Watches then model, Cmd.none
        else
            // Fire at most one watched run per tick (serialize). Per project:
            // sample HEAD; seed LastHead if unset; if it moved and no run is in
            // flight, run + advance LastHead. A busy project keeps its old
            // LastHead and re-fires next tick once free (coalesce).
            let mutable model' = model
            let mutable toRun = None
            for (pid, info) in Map.toList model.Watches do
                if Option.isNone toRun then
                    match projectRoot pid model'.Projects with
                    | None -> ()
                    | Some root ->
                        match info.LastHead, Watch.gitHead root with
                        | None, Some h ->
                            model' <- { model' with Watches = Map.add pid { info with LastHead = Some h } model'.Watches }
                        | Some last, Some h when h <> last ->
                            if not (hasActiveWatchRun pid model') then
                                model' <- { model' with Watches = Map.add pid { info with LastHead = Some h } model'.Watches }
                                toRun <- Some (pid, info.FlowId)
                        | _ -> ()
            match toRun with
            | Some (pid, flowId) -> startRun pid flowId Map.empty model'
            | None -> model', Cmd.none
    | StepSchemaLoaded (key, res) ->
        { model with
            StepSchemas = Map.add key res model.StepSchemas
            StepSchemasLoading = Set.remove key model.StepSchemasLoading }, Cmd.none
    | SelectStep (pid, flowId, idx) ->
        let model' = { model with SelectedStep = Some (pid, flowId, idx) }
        // Resolve the clicked step's task; fetch its describe schema (off the
        // UI thread) unless already cached/in-flight. Source + the form render
        // from the cache in the view.
        let stepTask =
            match projectRoot pid model.Projects, Map.tryFind pid model.ProjectFlows with
            | Some root, Some (FlowsOk flows) ->
                flows
                |> List.tryFind (fun f -> f.Id = flowId)
                |> Option.bind (fun f -> List.tryItem idx f.Steps)
                |> Option.map (fun step -> root, step)
            | _ -> None
        match stepTask with
        | None -> model', Cmd.none
        | Some (root, step) ->
            match resolveStepTask root step.Type with
            | None -> model', Cmd.none   // Inspector shows "task not found"
            | Some resolved ->
                let key = stepSchemaKey resolved.Path
                if Map.containsKey key model.StepSchemas || Set.contains key model.StepSchemasLoading then
                    model', Cmd.none
                else
                    let cmd : Cmd<Msg> =
                        [ fun dispatch ->
                            async {
                                do! Async.SwitchToThreadPool ()
                                let res =
                                    try Describe.schema (sdkAssemblyPath ()) resolved.Path step.Type
                                    with ex -> Error ex.Message
                                Dispatcher.UIThread.Post(fun () -> dispatch (StepSchemaLoaded (key, res)))
                            }
                            |> Async.Start ]
                    { model' with StepSchemasLoading = Set.add key model.StepSchemasLoading }, cmd
    | SetRunLogFilter (pid, runId, text) ->
        // A new query resets the match cursor to the first hit.
        { model with
            RunLogFilter   = Map.add (pid, runId) text model.RunLogFilter
            RunLogMatchIdx = Map.add (pid, runId) 0 model.RunLogMatchIdx }, Cmd.none
    | RunLogFindNext (pid, runId) ->
        let cur = Map.tryFind (pid, runId) model.RunLogMatchIdx |> Option.defaultValue 0
        { model with RunLogMatchIdx = Map.add (pid, runId) (cur + 1) model.RunLogMatchIdx }, Cmd.none
    | RunLogFindPrev (pid, runId) ->
        let cur = Map.tryFind (pid, runId) model.RunLogMatchIdx |> Option.defaultValue 0
        { model with RunLogMatchIdx = Map.add (pid, runId) (cur - 1) model.RunLogMatchIdx }, Cmd.none
    | DeleteSecret (pid, varName) ->
        // Delete from the keychain, then refresh the cached list so the
        // model changes and the Settings view re-renders without it.
        Secrets.delete pid varName |> ignore
        { model with
            ProjectSecrets = Map.add pid (Secrets.listForProject pid) model.ProjectSecrets },
        Cmd.none
    | LiveRunCompleted (key, result) ->
        match Map.tryFind key model.LiveRuns with
        | None -> model, Cmd.none  // should not happen; guard.
        | Some state ->
            let pid = state.ProjectId
            // Refresh history only if the Project is open (cached). If it's
            // closed, leave the cache untouched so we don't leave an orphan
            // entry that would short-circuit the lazy reload on next OpenProject.
            let newHistory = refreshHistoryIfOpen pid model
            // Keep the LiveRuns entry around if the tab is still open
            // (so the view can render the Completed phase); otherwise
            // drop it to bound the map.
            let newLiveRuns =
                if List.contains (LiveRun key) model.OpenTabs then
                    Map.add key { state with Phase = LiveCompleted result } model.LiveRuns
                else
                    Map.remove key model.LiveRuns
            { model with
                LiveRuns       = newLiveRuns
                ProjectHistory = newHistory },
            Cmd.none
    | LiveRunProgress (key, progress) ->
        // Merge a poller snapshot into the live state's Progress. Never
        // touches Phase, so it can't regress a Completed run back to
        // Pending; updating Progress even after completion just ensures
        // the final step states land if the last poller tick races the
        // executor's LiveRunCompleted. No-op if the tab is gone.
        match Map.tryFind key model.LiveRuns with
        | Some state ->
            { model with
                LiveRuns = Map.add key { state with Progress = progress } model.LiveRuns },
            Cmd.none
        | None -> model, Cmd.none
    | CancelLiveRun key ->
        // Drop a CANCEL flag in the run dir; the runner polls for it
        // (200ms) and kills the active step's process tree, ending the
        // run as Cancelled. Only actionable once the poller has matched
        // the run dir and while the run is still Pending.
        match Map.tryFind key model.LiveRuns with
        | Some state when (match state.Phase with LivePending -> true | _ -> false) ->
            match state.Progress.RunDir with
            | Some dir ->
                try File.WriteAllText(Path.Combine(dir, "CANCEL"), "") with _ -> ()
                { model with
                    LiveRuns =
                        Map.add key { state with CancelRequested = true } model.LiveRuns },
                Cmd.none
            | None -> model, Cmd.none
        | _ -> model, Cmd.none
    | ShowAddProject ->
        { model with
            AddProject =
                Some { Dir = ""; Name = ""; Engine = EngineKind.Unreal; Error = None } },
        Cmd.none
    | HideAddProject ->
        { model with AddProject = None }, Cmd.none
    | AddProjectSetDir dir ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some f ->
            { model with AddProject = Some { f with Dir = dir; Error = None } }, Cmd.none
    | AddProjectSetName name ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some f ->
            { model with AddProject = Some { f with Name = name; Error = None } }, Cmd.none
    | AddProjectSetEngine engine ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some f ->
            { model with AddProject = Some { f with Engine = engine; Error = None } }, Cmd.none
    | SubmitAddProject ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some form ->
            let withError msg =
                { model with AddProject = Some { form with Error = Some msg } }, Cmd.none
            let dir = form.Dir.Trim()
            if String.IsNullOrWhiteSpace dir then
                withError "Directory path is required."
            else
                try
                    // Scaffold the dir + .ci/ (project.toml + a runnable
                    // starter flow), then register. Creating the dir is the
                    // whole point of the wizard — it removes the CLI's
                    // "directory does not exist" / "no .ci/project.toml"
                    // friction. Existing files are never clobbered. Shared
                    // with the CLI `init` command via Core's Scaffold.
                    let absDir = Path.GetFullPath dir
                    let name =
                        if String.IsNullOrWhiteSpace form.Name then
                            Path.GetFileName(absDir.TrimEnd('\\', '/'))
                        else form.Name.Trim()
                    Scaffold.writeCi absDir name form.Engine |> ignore
                    match ProjectRegistry.add absDir (Some name) with
                    | ProjectRegistry.Added entry ->
                        // Refresh the registry-backed list and open the new
                        // project tab so the user lands somewhere useful.
                        let projects = ProjectRegistry.load ()
                        { model with
                            AddProject     = None
                            Projects       = projects
                            ProjectEngines = engineKindsFor projects },
                        Cmd.ofMsg (OpenProject entry.Name)
                    | ProjectRegistry.DuplicateName existing ->
                        withError
                            (sprintf "A project named '%s' is already registered (%s)."
                                existing.Name existing.Path)
                    | ProjectRegistry.InvalidPath reason ->
                        withError reason
                with ex ->
                    withError ex.Message
    | LiveRunFailed (key, ex) ->
        // Unexpected exception from the async machinery itself (not a
        // RunFailure, which is already a Result Error). Synthesize an
        // InternalError so the UI can show something rather than just
        // freezing in Pending.
        match Map.tryFind key model.LiveRuns with
        | None -> model, Cmd.none
        | Some state ->
            let result = Error (RunFailure.InternalError ex.Message)
            let pid = state.ProjectId
            let newHistory = refreshHistoryIfOpen pid model
            let newLiveRuns =
                if List.contains (LiveRun key) model.OpenTabs then
                    Map.add key { state with Phase = LiveCompleted result } model.LiveRuns
                else
                    Map.remove key model.LiveRuns
            { model with
                LiveRuns       = newLiveRuns
                ProjectHistory = newHistory },
            Cmd.none
