module Takatora.Gui.State

open System
open System.IO
open System.Text.Json
open Elmish
open Avalonia.Threading
open Takatora.Core

/// Project lookup key inside the GUI. The registry uses `Name` as the
/// stable identifier (per ProjectRegistry.find docs), so we mirror that
/// rather than introducing a separate id type.
type ProjectId = string

/// Run id (mirrors RunHistoryEntry.RunId). Carried alongside ProjectId
/// in RunDetail tabs because RunHistory.findRun needs the project's
/// working dir to locate the run.
type RunId = string

/// Client-side identifier for an in-flight LiveRun. Generated by the
/// GUI at RunFlow time and used as the LiveRun tab's key, because the
/// runner's RunId isn't known until Run.execute returns.
type LiveRunKey = Guid

/// State of one LiveRun tab. Captures enough to render before, during,
/// and after the run completes, without inventing a third "Cancelled
/// by tab close" state — closing the tab doesn't cancel the run, just
/// stops the GUI from observing it.
type LiveRunPhase =
    | LivePending
    | LiveCompleted of Result<RunOutcome, RunFailure>

/// Status of a single step as observed live from events.ndjson. Distinct
/// from Core.StepStatus because mid-run we have a "still running" state
/// the persisted record never has.
type LiveStepStatus =
    | StepRunning
    | StepOk
    | StepFailed
    | StepSkipped
    | StepCancelled

type LiveStep = {
    Id: string
    Type: string
    Status: LiveStepStatus
    DurationSec: float
}

/// A snapshot parsed from a run's events.ndjson + log.txt by the live
/// poller. Replaces the LiveRunState's previous snapshot wholesale on
/// each tick (cheap — these files are tiny).
type LiveProgress = {
    /// Discovered run dir, once the poller has matched it. None until then.
    RunDir: string option
    Steps: LiveStep list
    /// Tail of log.txt (most recent lines, capped).
    LogTail: string list
    /// True once a `run.end` event has been observed.
    Ended: bool
}

module LiveProgress =
    let empty = { RunDir = None; Steps = []; LogTail = []; Ended = false }

type LiveRunState = {
    ProjectId: ProjectId
    FlowId: string
    StartedAt: DateTimeOffset
    Phase: LiveRunPhase
    /// Latest live snapshot from the poller (steps + log tail).
    Progress: LiveProgress
    /// Set once the user clicks Cancel (we've written the CANCEL flag).
    /// Drives the button's "Cancelling…" / disabled state; the run keeps
    /// going until the runner observes the flag and tears down.
    CancelRequested: bool
}

/// Root tab variants. Home + Project + RunDetail + LiveRun are wired;
/// Settings (the app-wide one from gui.md) will land later.
type RootTab =
    | Home
    | Project of ProjectId
    | RunDetail of ProjectId * RunId
    | LiveRun of LiveRunKey

/// Sub-tabs inside a Project tab. Per gui.md these are plain TabControl
/// territory (only the root strip is custom), but we keep the active
/// sub-tab in the model so re-focusing a Project tab restores its
/// position rather than resetting to Flows.
type ProjectSubTab =
    | ProjectFlows
    | ProjectHistory
    | ProjectSettings

/// Result of trying to read a project's `.ci/flows.toml`. The three
/// outcomes need distinct UX — missing file is a setup hint, parse
/// failure is a config bug to surface, success is the happy path.
type FlowsLoad =
    | FlowsOk of Flow list
    | FlowsMissing
    | FlowsError of string

/// Add-Project wizard form state. Present (Some) when the wizard panel
/// on Home is open; None when collapsed. Kept in the model because
/// Elmish owns all UI state — there's no local widget state to lean on.
type AddProjectForm = {
    Dir: string
    Name: string
    Engine: EngineKind
    /// Last submission error, surfaced inline under the form. Cleared on
    /// the next edit/submit so a fixed mistake doesn't keep nagging.
    Error: string option
}

/// Same shape as FlowsLoad but for `.ci/project.toml`. Project info
/// is technically validated at `project add` time, but the file may
/// have been edited or deleted between registration and now.
type ProjectInfoLoad =
    | ProjectInfoOk of Project
    | ProjectInfoMissing
    | ProjectInfoError of string

type Model = {
    OpenTabs: RootTab list
    ActiveTab: RootTab
    Projects: ProjectRegistration list
    /// Per-Project-tab active sub-tab. Missing key means "default" (Flows).
    ProjectSubTabs: Map<ProjectId, ProjectSubTab>
    /// Cached `RunHistory.load` results, keyed by project id. Loaded
    /// lazily on OpenProject so initial app startup doesn't pay for
    /// every project's runs dir.
    ProjectHistory: Map<ProjectId, RunHistoryEntry list>
    /// Cached `TomlConfig.loadFlows` results, keyed by project id.
    /// Loaded on OpenProject alongside history.
    ProjectFlows: Map<ProjectId, FlowsLoad>
    /// Cached `TomlConfig.loadProject` results, keyed by project id.
    /// Loaded on OpenProject alongside flows.
    ProjectInfo: Map<ProjectId, ProjectInfoLoad>
    /// Cached `RunHistory.findRun` results for open RunDetail tabs,
    /// keyed by (project, run id). Loaded on OpenRunDetail, dropped
    /// when the corresponding tab closes.
    RunDetails: Map<ProjectId * RunId, RunHistoryEntry * StepSummary list>
    /// Live state of every LiveRun tab the user has kicked off. Entries
    /// are added by RunFlow and removed by LiveRunCompleted (which also
    /// drops the entry if its tab has been closed).
    LiveRuns: Map<LiveRunKey, LiveRunState>
    /// Add-Project wizard state. None = panel collapsed; Some = open with
    /// in-progress field values. Lives on the Home tab.
    AddProject: AddProjectForm option
}

type Msg =
    | RefreshProjects
    | OpenProject of ProjectId
    | ActivateTab of RootTab
    | CloseTab of RootTab
    | ActivateSubTab of ProjectId * ProjectSubTab
    | RefreshHistory of ProjectId
    | RefreshFlows of ProjectId
    | RefreshProjectInfo of ProjectId
    | OpenRunDetail of ProjectId * RunId
    | RunFlow of ProjectId * flowId:string
    | LiveRunCompleted of LiveRunKey * Result<RunOutcome, RunFailure>
    | LiveRunProgress  of LiveRunKey * LiveProgress
    | LiveRunFailed    of LiveRunKey * exn
    | CancelLiveRun    of LiveRunKey
    // Add-Project wizard
    | ShowAddProject
    | HideAddProject
    | AddProjectSetDir    of string
    | AddProjectSetName   of string
    | AddProjectSetEngine of EngineKind
    | SubmitAddProject

let init () : Model * Cmd<Msg> =
    { OpenTabs       = [ Home ]
      ActiveTab      = Home
      Projects       = ProjectRegistry.load ()
      ProjectSubTabs = Map.empty
      ProjectHistory = Map.empty
      ProjectFlows   = Map.empty
      ProjectInfo    = Map.empty
      RunDetails     = Map.empty
      LiveRuns       = Map.empty
      AddProject     = None },
    Cmd.none

let private moveOrAppend (tab: RootTab) (tabs: RootTab list) : RootTab list =
    if List.contains tab tabs then tabs else tabs @ [ tab ]

/// Compute the post-close tab list plus the next active tab. When the
/// closed tab was the active one, prefer the tab that was to its right
/// (browser convention); fall back to the previous tab, finally Home.
let private closeAndPickActive
        (target: RootTab) (active: RootTab) (tabs: RootTab list)
        : RootTab list * RootTab =
    if target = Home then tabs, active
    else
        match List.tryFindIndex ((=) target) tabs with
        | None -> tabs, active
        | Some idx ->
            let newTabs = List.filter ((<>) target) tabs
            let newActive =
                if active <> target then active
                elif idx < List.length newTabs then newTabs.[idx]
                else
                    match newTabs with
                    | [] -> Home
                    | _  -> List.last newTabs
            newTabs, newActive

/// Look up the active sub-tab for a project, defaulting to Flows. Used
/// by views; not used by `update` (which writes the map directly).
let projectSubTab (pid: ProjectId) (model: Model) : ProjectSubTab =
    Map.tryFind pid model.ProjectSubTabs
    |> Option.defaultValue ProjectFlows

let private projectRoot
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : string option =
    projects
    |> List.tryFind (fun (p: ProjectRegistration) -> p.Name = pid)
    |> Option.map (fun p -> p.Path)

let private loadHistoryFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : RunHistoryEntry list =
    match projectRoot pid projects with
    | Some root -> RunHistory.load root
    | None      -> []

/// Reload a project's history into the cache, but only if it's already
/// cached — i.e. the Project tab is open (CloseTab drops the entry).
/// Used after a run completes so a visible History sub-tab updates
/// without manual Refresh, while avoiding orphan cache entries for
/// closed projects (which would otherwise defeat OpenProject's lazy
/// reload on the next open).
let private refreshHistoryIfOpen
        (pid: ProjectId)
        (model: Model)
        : Map<ProjectId, RunHistoryEntry list> =
    if Map.containsKey pid model.ProjectHistory then
        Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory
    else model.ProjectHistory

/// Read and classify `.ci/flows.toml` for the given project. We keep
/// the three outcomes distinct because each maps to a different UX:
/// missing → "no flows yet, here's how to add one"; error → "your
/// flows.toml has a bug, here's the message"; ok → render the list.
let private loadFlowsFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : FlowsLoad =
    match projectRoot pid projects with
    | None -> FlowsError (sprintf "Project '%s' not in registry" pid)
    | Some root ->
        let path = Path.Combine(root, ".ci", "flows.toml")
        if not (File.Exists path) then FlowsMissing
        else
            try FlowsOk (TomlConfig.loadFlows path)
            with ex -> FlowsError ex.Message

/// Resolve the Tasks SDK assembly + builtin tasks dir from the host
/// process layout. Same defaults the CLI uses; works here because the
/// GUI project-references Takatora.Tasks + Takatora.Tasks.Builtin, so
/// Tasks.dll + builtin-tasks/ get copied next to the GUI executable.
let private sdkAssemblyPath () =
    Path.Combine(AppContext.BaseDirectory, "Takatora.Tasks.dll")

let private builtinTasksDir () =
    Path.Combine(AppContext.BaseDirectory, "builtin-tasks")

// ─── Live run tailing ───────────────────────────────────────────────
//
// The runner writes events.ndjson + log.txt under
// `<root>/.ci/runs/<runId>/` while it executes (each step appends as it
// goes). The GUI never learns the runId — Run.execute generates it
// internally — so we detect the new run dir by diffing `.ci/runs/`
// against a snapshot captured the instant before the run starts, then
// poll that dir on a background thread, marshaling snapshots to the UI.

/// Run-dir names present under `<root>/.ci/runs/` right now. Captured at
/// launch so the poller can spot the one this run creates.
let private existingRunDirs (root: string) : Set<string> =
    let runsDir = Path.Combine(root, ".ci", "runs")
    if Directory.Exists runsDir then
        Directory.GetDirectories runsDir
        |> Array.map Path.GetFileName
        |> Set.ofArray
    else Set.empty

/// The newest run dir under `<root>/.ci/runs/` not present in `before`.
/// Run ids sort lexicographically by time, so the max name is the latest.
let private findNewRunDir (root: string) (before: Set<string>) : string option =
    let runsDir = Path.Combine(root, ".ci", "runs")
    if not (Directory.Exists runsDir) then None
    else
        Directory.GetDirectories runsDir
        |> Array.map Path.GetFileName
        |> Array.filter (fun n -> not (Set.contains n before))
        |> Array.sortDescending
        |> Array.tryHead
        |> Option.map (fun n -> Path.Combine(runsDir, n))

/// Read all non-empty lines from a file the runner may be appending to
/// concurrently. FileShare.ReadWrite avoids fighting the writer's lock.
let private readSharedLines (path: string) : string list =
    try
        if not (File.Exists path) then []
        else
            use fs =
                new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)
            use sr = new StreamReader(fs)
            sr.ReadToEnd().Split('\n')
            |> Array.choose (fun l ->
                let t = l.TrimEnd('\r')
                if t.Trim() = "" then None else Some t)
            |> Array.toList
    with _ -> []

let private maxLogTail = 300

/// Parse a run dir's events.ndjson + log.txt into a LiveProgress
/// snapshot. Tolerant of partial/garbled trailing lines (the writer may
/// be mid-append) — bad lines are skipped rather than failing the tick.
let private readProgress (runDir: string) : LiveProgress =
    let events = readSharedLines (Path.Combine(runDir, "events.ndjson"))
    // Ordered, de-duplicated step list keyed by step_id.
    let steps = System.Collections.Generic.List<LiveStep>()
    let indexOf (id: string) =
        let mutable found = -1
        for i in 0 .. steps.Count - 1 do
            if steps.[i].Id = id then found <- i
        found
    let upsert (id: string) (typ: string) (status: LiveStepStatus) (dur: float) =
        let i = indexOf id
        let step = { Id = id; Type = typ; Status = status; DurationSec = dur }
        if i < 0 then steps.Add step else steps.[i] <- step
    let mutable ended = false
    for line in events do
        try
            use doc = JsonDocument.Parse(line)
            let root = doc.RootElement
            let str (name: string) =
                match root.TryGetProperty name with
                | true, v when v.ValueKind = JsonValueKind.String -> v.GetString()
                | _ -> ""
            let num (name: string) =
                match root.TryGetProperty name with
                | true, v when v.ValueKind = JsonValueKind.Number -> v.GetDouble()
                | _ -> 0.0
            match str "kind" with
            | "step.start" -> upsert (str "step_id") (str "type") StepRunning 0.0
            | "step.end" ->
                let status =
                    match str "status" with
                    | "success"   -> StepOk
                    | "cancelled" -> StepCancelled
                    | _           -> StepFailed
                upsert (str "step_id") (str "type") status (num "duration_sec")
            | "step.skip" -> upsert (str "step_id") (str "type") StepSkipped 0.0
            | "run.end"   -> ended <- true
            | _ -> ()
        with _ -> ()
    let logTail =
        let all = readSharedLines (Path.Combine(runDir, "log.txt"))
        if List.length all > maxLogTail then
            all |> List.skip (List.length all - maxLogTail)
        else all
    { RunDir = Some runDir; Steps = List.ofSeq steps; LogTail = logTail; Ended = ended }

/// Same shape as `loadFlowsFor` but for `.ci/project.toml`.
let private loadProjectInfoFor
        (pid: ProjectId)
        (projects: ProjectRegistration list)
        : ProjectInfoLoad =
    match projectRoot pid projects with
    | None -> ProjectInfoError (sprintf "Project '%s' not in registry" pid)
    | Some root ->
        let path = Path.Combine(root, ".ci", "project.toml")
        if not (File.Exists path) then ProjectInfoMissing
        else
            try ProjectInfoOk (TomlConfig.loadProject path)
            with ex -> ProjectInfoError ex.Message

let private engineTypeToken = function
    | EngineKind.Unreal -> "unreal"
    | EngineKind.Unity  -> "unity"
    | EngineKind.Godot  -> "godot"

/// Minimal valid `project.toml` body for a freshly scaffolded project.
/// Only the keys `TomlConfig.parseProject` requires (project.name /
/// working_dir + engine.type) plus a sensible history default. Engine
/// paths are left for autodetection — same as a hand-written stub.
let private scaffoldProjectToml (name: string) (engine: EngineKind) : string =
    let esc (s: string) = s.Replace("\\", "\\\\").Replace("\"", "\\\"")
    String.concat "\n" [
        "# Generated by Takatora GUI — Add Project wizard."
        "# Edit to point at your engine install / project file as needed."
        ""
        "[project]"
        sprintf "name = \"%s\"" (esc name)
        "working_dir = \".\""
        ""
        "[engine]"
        sprintf "type = \"%s\"" (engineTypeToken engine)
        ""
        "[history]"
        "keep_last_n_runs = 50"
        ""
    ]

/// Starter `flows.toml` so a freshly scaffolded project has one
/// immediately-runnable flow. Uses `notify.console` — the only
/// engine-agnostic builtin that runs without an engine install — so
/// the smoke flow works regardless of the chosen EngineKind.
let private scaffoldFlowsToml () : string =
    String.concat "\n" [
        "# Generated by Takatora GUI — Add Project wizard."
        "# A starter flow you can run right away; replace with your real"
        "# build/cook/export steps as you wire up the engine."
        ""
        "[[flow]]"
        "id = \"smoke\""
        "name = \"Smoke test (notify only)\""
        ""
        "[flow.vars]"
        "message = { type = \"string\", default = \"hello from takatora\" }"
        ""
        "[[flow.steps]]"
        "type = \"notify.console\""
        ""
    ]

let update (msg: Msg) (model: Model) : Model * Cmd<Msg> =
    match msg with
    | RefreshProjects ->
        { model with Projects = ProjectRegistry.load () }, Cmd.none
    | OpenProject pid ->
        let tab = Project pid
        let history =
            if Map.containsKey pid model.ProjectHistory then model.ProjectHistory
            else Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory
        let flows =
            if Map.containsKey pid model.ProjectFlows then model.ProjectFlows
            else Map.add pid (loadFlowsFor pid model.Projects) model.ProjectFlows
        let info =
            if Map.containsKey pid model.ProjectInfo then model.ProjectInfo
            else Map.add pid (loadProjectInfoFor pid model.Projects) model.ProjectInfo
        { model with
            OpenTabs       = moveOrAppend tab model.OpenTabs
            ActiveTab      = tab
            ProjectHistory = history
            ProjectFlows   = flows
            ProjectInfo    = info },
        Cmd.none
    | ActivateTab tab ->
        if List.contains tab model.OpenTabs then
            { model with ActiveTab = tab }, Cmd.none
        else model, Cmd.none
    | CloseTab tab ->
        let newTabs, newActive = closeAndPickActive tab model.ActiveTab model.OpenTabs
        // Drop per-tab caches when the corresponding tab closes; reopen
        // reloads from disk anyway, and keeping stale entries would let
        // the cache grow without bound across a long session.
        //
        // LiveRuns entries are intentionally NOT dropped here for tabs
        // closed while still Pending — LiveRunCompleted needs the entry
        // to find the project id for the post-run history refresh. It
        // drops the entry itself when it sees the tab is no longer in
        // OpenTabs.
        let subTabs, history, flows, info, details =
            match tab with
            | Project pid ->
                Map.remove pid model.ProjectSubTabs,
                Map.remove pid model.ProjectHistory,
                Map.remove pid model.ProjectFlows,
                Map.remove pid model.ProjectInfo,
                model.RunDetails
            | RunDetail (pid, runId) ->
                model.ProjectSubTabs,
                model.ProjectHistory,
                model.ProjectFlows,
                model.ProjectInfo,
                Map.remove (pid, runId) model.RunDetails
            | LiveRun _ | Home ->
                model.ProjectSubTabs,
                model.ProjectHistory,
                model.ProjectFlows,
                model.ProjectInfo,
                model.RunDetails
        { model with
            OpenTabs       = newTabs
            ActiveTab      = newActive
            ProjectSubTabs = subTabs
            ProjectHistory = history
            ProjectFlows   = flows
            ProjectInfo    = info
            RunDetails     = details },
        Cmd.none
    | ActivateSubTab (pid, sub) ->
        { model with ProjectSubTabs = Map.add pid sub model.ProjectSubTabs }, Cmd.none
    | RefreshHistory pid ->
        { model with
            ProjectHistory = Map.add pid (loadHistoryFor pid model.Projects) model.ProjectHistory },
        Cmd.none
    | RefreshFlows pid ->
        { model with
            ProjectFlows = Map.add pid (loadFlowsFor pid model.Projects) model.ProjectFlows },
        Cmd.none
    | RefreshProjectInfo pid ->
        { model with
            ProjectInfo = Map.add pid (loadProjectInfoFor pid model.Projects) model.ProjectInfo },
        Cmd.none
    | OpenRunDetail (pid, runId) ->
        let tab = RunDetail (pid, runId)
        let key = pid, runId
        let details =
            if Map.containsKey key model.RunDetails then model.RunDetails
            else
                match projectRoot pid model.Projects with
                | None -> model.RunDetails
                | Some root ->
                    match RunHistory.findRun root runId with
                    | Some data -> Map.add key data model.RunDetails
                    | None      -> model.RunDetails
        { model with
            OpenTabs   = moveOrAppend tab model.OpenTabs
            ActiveTab  = tab
            RunDetails = details },
        Cmd.none
    | RunFlow (pid, flowId) ->
        // Async in-process run: spin up a LiveRun tab immediately so
        // the user sees the dispatch land, then schedule Run.execute on
        // the thread pool. LiveRunCompleted (or LiveRunFailed on an
        // unexpected exn) closes the loop by updating the tab's phase
        // and reloading history.
        match projectRoot pid model.Projects with
        | None -> model, Cmd.none
        | Some root ->
            let key = Guid.NewGuid()
            let tab = LiveRun key
            let liveState = {
                ProjectId = pid
                FlowId    = flowId
                StartedAt = DateTimeOffset.UtcNow
                Phase     = LivePending
                Progress  = LiveProgress.empty
                CancelRequested = false
            }
            // Snapshot the runs dir before launching so the poller can
            // identify the dir this run is about to create.
            let runsBefore = existingRunDirs root
            let opts : Run.Options = {
                WorkingDir       = root
                FlowId           = flowId
                VarOverrides     = Map.empty
                SdkAssemblyPath  = sdkAssemblyPath ()
                BuiltinTasksDir  = builtinTasksDir ()
                UserTasksDir     = None
            }
            // Run on the thread pool, then marshal the result message
            // back onto the Avalonia UI thread before dispatching.
            //
            // We deliberately do NOT use Cmd.OfAsync.either here: in
            // Elmish, the dispatch loop runs `setState` (→ FuncUI's
            // host.Update → Avalonia view rebuild) on whatever thread
            // calls `dispatch`. FuncUI.Elmish 1.5.1's withHost does not
            // marshal, so dispatching from the thread-pool thread would
            // rebuild the view off the UI thread and crash the whole
            // app. Dispatcher.UIThread.Post guarantees the dispatch —
            // and thus the re-render — happens on the UI thread.
            let runCmd : Cmd<Msg> =
                [ fun dispatch ->
                    async {
                        do! Async.SwitchToThreadPool ()
                        let msg =
                            try LiveRunCompleted (key, Run.execute opts)
                            with ex -> LiveRunFailed (key, ex)
                        Dispatcher.UIThread.Post(fun () -> dispatch msg)
                    }
                    |> Async.Start ]
            // Independent tail poller. Reads the run's events/log files
            // (which Run.execute appends to live) every ~300ms and posts
            // a LiveRunProgress snapshot to the UI thread, until it sees
            // a run.end event or hits the safety cap. Runs concurrently
            // with the executor above; both are UI-thread-safe via Post.
            let pollCmd : Cmd<Msg> =
                [ fun dispatch ->
                    async {
                        do! Async.SwitchToThreadPool ()
                        let mutable runDir = None
                        let mutable finished = false
                        let mutable ticks = 0
                        // Cap ~ 1 hour at 300ms cadence; a stuck run won't
                        // poll forever if run.end is somehow never written.
                        while not finished && ticks < 12000 do
                            ticks <- ticks + 1
                            if Option.isNone runDir then
                                runDir <- findNewRunDir root runsBefore
                            match runDir with
                            | Some dir ->
                                let progress = readProgress dir
                                Dispatcher.UIThread.Post(fun () ->
                                    dispatch (LiveRunProgress (key, progress)))
                                if progress.Ended then finished <- true
                            | None -> ()
                            if not finished then do! Async.Sleep 300
                    }
                    |> Async.Start ]
            { model with
                OpenTabs  = moveOrAppend tab model.OpenTabs
                ActiveTab = tab
                LiveRuns  = Map.add key liveState model.LiveRuns },
            Cmd.batch [ runCmd; pollCmd ]
    | LiveRunCompleted (key, result) ->
        match Map.tryFind key model.LiveRuns with
        | None -> model, Cmd.none  // should not happen; guard.
        | Some state ->
            let pid = state.ProjectId
            // Refresh history only if the Project is open (cached). If it's
            // closed, leave the cache untouched so we don't leave an orphan
            // entry that would short-circuit the lazy reload on next OpenProject.
            let newHistory = refreshHistoryIfOpen pid model
            // Keep the LiveRuns entry around if the tab is still open
            // (so the view can render the Completed phase); otherwise
            // drop it to bound the map.
            let newLiveRuns =
                if List.contains (LiveRun key) model.OpenTabs then
                    Map.add key { state with Phase = LiveCompleted result } model.LiveRuns
                else
                    Map.remove key model.LiveRuns
            { model with
                LiveRuns       = newLiveRuns
                ProjectHistory = newHistory },
            Cmd.none
    | LiveRunProgress (key, progress) ->
        // Merge a poller snapshot into the live state's Progress. Never
        // touches Phase, so it can't regress a Completed run back to
        // Pending; updating Progress even after completion just ensures
        // the final step states land if the last poller tick races the
        // executor's LiveRunCompleted. No-op if the tab is gone.
        match Map.tryFind key model.LiveRuns with
        | Some state ->
            { model with
                LiveRuns = Map.add key { state with Progress = progress } model.LiveRuns },
            Cmd.none
        | None -> model, Cmd.none
    | CancelLiveRun key ->
        // Drop a CANCEL flag in the run dir; the runner polls for it
        // (200ms) and kills the active step's process tree, ending the
        // run as Cancelled. Only actionable once the poller has matched
        // the run dir and while the run is still Pending.
        match Map.tryFind key model.LiveRuns with
        | Some state when (match state.Phase with LivePending -> true | _ -> false) ->
            match state.Progress.RunDir with
            | Some dir ->
                try File.WriteAllText(Path.Combine(dir, "CANCEL"), "") with _ -> ()
                { model with
                    LiveRuns =
                        Map.add key { state with CancelRequested = true } model.LiveRuns },
                Cmd.none
            | None -> model, Cmd.none
        | _ -> model, Cmd.none
    | ShowAddProject ->
        { model with
            AddProject =
                Some { Dir = ""; Name = ""; Engine = EngineKind.Unreal; Error = None } },
        Cmd.none
    | HideAddProject ->
        { model with AddProject = None }, Cmd.none
    | AddProjectSetDir dir ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some f ->
            { model with AddProject = Some { f with Dir = dir; Error = None } }, Cmd.none
    | AddProjectSetName name ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some f ->
            { model with AddProject = Some { f with Name = name; Error = None } }, Cmd.none
    | AddProjectSetEngine engine ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some f ->
            { model with AddProject = Some { f with Engine = engine; Error = None } }, Cmd.none
    | SubmitAddProject ->
        match model.AddProject with
        | None -> model, Cmd.none
        | Some form ->
            let withError msg =
                { model with AddProject = Some { form with Error = Some msg } }, Cmd.none
            let dir = form.Dir.Trim()
            if String.IsNullOrWhiteSpace dir then
                withError "Directory path is required."
            else
                try
                    // Scaffold the dir + .ci/project.toml, then register.
                    // Creating the dir is the whole point of the wizard —
                    // it removes the CLI's "directory does not exist" /
                    // "no .ci/project.toml" friction. An existing
                    // project.toml is left untouched (we just register it).
                    let absDir = Path.GetFullPath dir
                    let ciDir  = Path.Combine(absDir, ".ci")
                    Directory.CreateDirectory ciDir |> ignore
                    let tomlPath = Path.Combine(ciDir, "project.toml")
                    let name =
                        if String.IsNullOrWhiteSpace form.Name then
                            Path.GetFileName(absDir.TrimEnd('\\', '/'))
                        else form.Name.Trim()
                    if not (File.Exists tomlPath) then
                        File.WriteAllText(tomlPath, scaffoldProjectToml name form.Engine)
                    // Drop in a runnable starter flow too, so the new
                    // project isn't stuck at "no flows.toml". Existing
                    // flows are never clobbered.
                    let flowsPath = Path.Combine(ciDir, "flows.toml")
                    if not (File.Exists flowsPath) then
                        File.WriteAllText(flowsPath, scaffoldFlowsToml ())
                    match ProjectRegistry.add absDir (Some name) with
                    | ProjectRegistry.Added entry ->
                        // Refresh the registry-backed list and open the new
                        // project tab so the user lands somewhere useful.
                        { model with
                            AddProject = None
                            Projects   = ProjectRegistry.load () },
                        Cmd.ofMsg (OpenProject entry.Name)
                    | ProjectRegistry.DuplicateName existing ->
                        withError
                            (sprintf "A project named '%s' is already registered (%s)."
                                existing.Name existing.Path)
                    | ProjectRegistry.InvalidPath reason ->
                        withError reason
                with ex ->
                    withError ex.Message
    | LiveRunFailed (key, ex) ->
        // Unexpected exception from the async machinery itself (not a
        // RunFailure, which is already a Result Error). Synthesize an
        // InternalError so the UI can show something rather than just
        // freezing in Pending.
        match Map.tryFind key model.LiveRuns with
        | None -> model, Cmd.none
        | Some state ->
            let result = Error (RunFailure.InternalError ex.Message)
            let pid = state.ProjectId
            let newHistory = refreshHistoryIfOpen pid model
            let newLiveRuns =
                if List.contains (LiveRun key) model.OpenTabs then
                    Map.add key { state with Phase = LiveCompleted result } model.LiveRuns
                else
                    Map.remove key model.LiveRuns
            { model with
                LiveRuns       = newLiveRuns
                ProjectHistory = newHistory },
            Cmd.none
